### ISSUE TITLE
Overwrite default configs patterns not found

### ISSUE THREAD

**Issue by wellyal** [prettier/vim-prettier#102]
Have I missed something. I am trying to overwrite the default configs from my /.vimrc but when I try to run vim I got this.

Pattern not found: prettier#config#print_width = 100
Pattern not found: prettier#config#tab_width = 2
Pattern not found: prettier#config#use_tabs = 'false'
Pattern not found: prettier#config#semi = 'false'
Pattern not found: prettier#config#single_quote = 'true'
Pattern not found: prettier#config#bracket_spacing = 'true'
Pattern not found: prettier#config#jsx_bracket_same_line = 'false'
Pattern not found: prettier#config#arrow_parens = 'avoid'
Pattern not found: prettier#config#trailing_comma = 'none'
Pattern not found: prettier#config#parser = 'babylon'
Pattern not found: prettier#config#config_precedence = 'prefer-file'
Pattern not found: prettier#config#prose_wrap = 'preserve'

**Comment by mitermayer** [comment]
Hi @wellyal,

Can you please paste here how you are overwriting the above on your .vimrc ? also what vim version ? what OS ?

Thanks!

**Comment by mtsznowak** [comment]
I have encountered the same issue (NVIM v0.2.2). I don't know why, but prepending every line of config with `let` solved the problem, e.g.
```let g:prettier#config#print_width = 80```

**Comment by mitermayer** [comment]
Hi @mtsznowak ,

The global configuration variables are meant to be overwritten with `let g:foo = "bar"` syntax, glad you figured it out. 

@wellyal  does that solve your problem as well ? 

Will close this issue for now, if you still experience same issue please feel free to reopen. Also feel free to leave any comments in here!

Thanks a lot :)

**Comment by wellyal** [comment]
Yes, totally. thx

**Comment by chris-kobrzak** [comment]
Hey @mitermayer, would it make sense to update the "Overwrite default prettier configuration" section in the project's README to include these `let` keywords? Needless to say, I've just fallen into the same trap ☺️

**Comment by mitermayer** [comment]
Hi @chris-kobrzak,

I may be missing something, but the `let` keywords are on the README, check https://github.com/prettier/vim-prettier/blob/master/README.md#configuration 

Its also on the docs inside vim when you do `:help prettier`

**Comment by chris-kobrzak** [comment]
Sorry for the confusion @mitermayer. I was referring to the [config overrides section](https://github.com/prettier/vim-prettier/blob/master/README.md#overwrite-default-prettier-configuration).

It's a minor issue and I'm happy to submit a PR if you'd be happy to merge it.

**Comment by mitermayer** [comment]
Hi @chris-kobrzak,

Wow! I haven't noticed that that area was missing the `let ` !! You all were right in here and I was wrong! I am sorry!

Please do submit a PR for it and it will be greatly appreciated!
