### ISSUE TITLE
Update DOC's and README

### ISSUE THREAD

**Issue by mitermayer** [prettier/vim-prettier#106]
It has been a long time since we updated the README, and it feels like we just keep adding new extensions on the code usage. We should make sure we have a very clear and unambiguous README, some FAQ area and a clear examples of suggestions of integrations. 

Would be amazing if someone from the community could tackle this work :)

**Comment by huyvohcmc** [comment]
I would like to update the readme, but firstly what are your specific expectations? Like you can list down some problems and I'll see what I can do.

**Comment by mitermayer** [comment]
Hi @huyvohcmc ,

I am currently working on `vim-prettier` 1.0 there will be some config and default changes, if you are still interested once we have a beta version I can provide you a list of changes and you can have free power to fully re-edit the README and docs to better explain the changes. 

I was also thinking about including a FAQ section area on the front. If this is something that would interest you I can try to reach you offline and we can work together on it

**Comment by huyvohcmc** [comment]
@mitermayer Sure, I'll try my best.

**Comment by mitermayer** [comment]
Getting close to having all features for 1.x developed then we will get back to this issue

**Comment by mitermayer** [comment]
This is being handled on the `release/1.x` branch
