### ISSUE TITLE
Error infinite loop Prettier: failed to parse buffer

### ISSUE THREAD

**Issue by alanhamlett** [prettier/vim-prettier#113]
### Reproduction steps:

1. modify file in buffer 1 without saving
2. switch to buffer 2
3. modify file and `:w`
4. switch back to buffer 1

Error appears forever, until restarting Vim.

![prettier-bug](https://user-images.githubusercontent.com/522344/35883312-af8887ce-0b3b-11e8-8f18-d4f5388cd2e2.gif)

**Comment by mitermayer** [comment]
Thanks @alanhamlett,

I will investigate this as soon as I have some free time. This is a tricky race condition problem to solve. 

Do you mind also providing some minimal code for buffer 1 and buffer 2 so that I can try to replicate locally while attempting to work on a fix for it ?

**Comment by alanhamlett** [comment]
I was using prettier version `1.7.4`, after upgrading to `1.10.2` I haven't noticed it happening. Probably still a bug, just not triggered unless prettier fails to parse the file?

**Comment by mitermayer** [comment]
I haven't had time to investigate this yet, lets leave this issue open to see if anyone hits on it in the next week or so, otherwise we close it. 

Thanks again for all your help @alanhamlett !

**Comment by Kachulio1** [comment]
@mitermayer I don't know if this will help I had the same problem like this one in this  [issue](https://github.com/prettier/vim-prettier/issues/108):-

`Prettier: failed to parse buffer`

It turned out that in my case I had installed prettier using fishshell and when I switch to `zsh`  I encountered the problem. 
You must use the same command line shell that you installed prettier with, in order for you not to get the error.

**Comment by mitermayer** [comment]
I think we fixed this on `1.x` branch, will double check in there and if thats the case will port back a fix to master repo

**Comment by mitermayer** [comment]
@SamHowie, @docwhat, if any of you have sometime and can reproduce this issue, would be great to have it fixed on 1.x branch as we are getting pretty close to have a beta.

**Comment by mitermayer** [comment]
This is currently fixed on `release/1.x` branch which soon will be merged to mater
