### ISSUE TITLE
Format without saving

### ISSUE THREAD

**Issue by nikolvs** [prettier/vim-prettier#116]
Is there a way to format a file without automatically saving it? I read the docs, but didn't find anything about it there. If not, is it possible to implement this feature as an option? Thanks!

**Comment by mitermayer** [comment]
Hi @nikolvs 

Hi @nikolvs,

Thanks for raising this question. Prettier async always saves the file, but if you run the synchronous version it should'nt save it.

`:Prettier` 

One common problem is when you setup your `.vimrc` to use `async` by default with:

```viml
let g:prettier#exec_cmd_async = 1
```

The above will cause `:Prettier` to run as an alias for `:PrettierAsync`.

**Comment by mitermayer** [comment]
Please try the above and let me know if that solve your problem (removing the flag that forces async formatting from your .vimrc)

**Comment by mitermayer** [comment]
I also wonder how could we solve this problem differently, Im not sure if adding yet another configuration option is the right solution since that would make thing even harder to configure

**Comment by nikolvs** [comment]
Hey @mitermayer, that solved my problem! Thanks!!

**Comment by AngeloMateus** [comment]
Is there any chance async would work without saving the buffer?

**Comment by mitermayer** [comment]
@AngeloMateus  feel free to submit this as a separate issue and I can look into it, should not be a problem.
