### ISSUE TITLE
Is there a prettier.eslintIntegration config

### ISSUE THREAD

**Issue by wellyal** [prettier/vim-prettier#117]
I would like my prettier to read all configs from my eslint. Is there a support for this issue. I haven't found in the doc.

**Comment by mitermayer** [comment]
Hi @wellyal,

Thanks for raising this question, `vim-prettier` is a wrapper for `prettier` and will support all `prettier` API. 

The way we currently handle configuration is by passing to `prettier` itself the configuration file or where to find it, we do not read the config file. 

For `vim-prettier` to start supporting `.eslintintegration` config files `prettier` itself will need to have support for it
