### ISSUE TITLE
Can't spot why prettier fails to parse css: "1 col 6| Unexpected token, expected ;"

### ISSUE THREAD

**Issue by therealplato** [prettier/vim-prettier#118]
Hi, after searching I saw other issues causing this error string, caused by syntax errors or incomplete expressions passed to the engine. I'm observing it when saving a css file.

I have installed prettier with `  Plug 'prettier/vim-prettier', { 'do': 'yarn install' }`
I have configured prettier with:
```
augroup js
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue PrettierAsync
au FileType js,html nmap <Leader>d :TernDef<CR>
au FileType js,html nmap <Leader>r :TernRename<CR>
let g:prettier#autoformat = 0
let g:prettier#config#single_quote = 'false'
let g:prettier#config#print_width = 120
let g:prettier#config#parser = 'babylon'
augroup END
```
The file I'm saving, `foo.css`:
```
label {
  display: block;
}
input[type="text"] {
  margin-bottom: 0.5em;
}
nav {
  background-color: LightCyan;
  padding: 1em;
}
#mevents {
  background-color:LightGoldenRodYellow;
  overflow:auto;
}
.grid {
  display: grid;
  box-sizing: border-box;
  width: 100vw;
  height: 100vh;
  grid-template-columns: 1fr 3fr;
  grid-gap: 1px;
  background-color: grey;
}
.left {
  grid-column-start: 1;
}
.right {
  grid-column-start: 2;
}
```
`:messages` shows "Prettier: failed to parse buffer."
Should Prettier succeed in parsing/formatting this CSS file?

**Comment by mitermayer** [comment]
Hi @therealplato,

Thanks for submitting this issue, could you please provide me a bit more information in order for me be able to help debugging your issue ?

can you please provide me the output of the commands

* `:PrettierVersion` 
* `:PrettierCliVersion`
* `:PrettierCliPath`

Also can you try commenting out that line from your `.vimrc`:

from:
```viml
let g:prettier#config#parser = 'babylon'
```

to:
```viml
" let g:prettier#config#parser = 'babylon'
```
*** 

I wonder if you are using an older combination of `vim-prettier` and/or `prettier` CLI. Also it could be a bug where `prettier` is giving more precedence to the passed `parser` as opposed to the lang one. 


 I think if you can provide the above information I will be able to better understand what is happening and if it is a bug or just incompatible usage of prettier versions

**Comment by therealplato** [comment]
```
    :PrettierVersion
0.2.6
    :PrettierCliVersion
Usage: prettier [opts] [filename ...]^@^@Available options:^@  --write              Edit the file in-place (beware!)^@  --stdin              Read input from
stdin^@  --print-width <int>  Specify the length of line that the printer will wrap on. Defaults to 80.^@  --tab-width <int>    Specify the number of spaces
per indentation-level. Defaults to 2.^@  --flow-parser        Use the flow parser instead of babylon^@  --single-quote       Use single quotes instead of dou
ble^@  --trailing-comma     Print trailing commas wherever possible^@  --bracket-spacing    Put spaces between brackets. Defaults to true, set false to turn
off^@
    :PrettierCliPath
prettier
```
:joy:
All good after `yarn global add prettier` installed `1.11.1`.
