### ISSUE TITLE
Support for language-specific settings

### ISSUE THREAD

**Issue by czosel** [prettier/vim-prettier#121]
Hi, 

first of all: thanks for this awesome plugin :wink: 

Is it possible to configure prettier differently depending on the language? My current issue is that I need a tab-width of 4, but only for markdown files. I tried something like
```
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.vue PrettierAsync
autocmd BufWritePre *.md PrettierAsync --tab-width 4
```
but i guess PrettierAsync doesn't even accept CLI options.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
0.2.6
**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.11.1
**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
prettier

**Comment by mitermayer** [comment]
Hi @czosel,

Thanks for raising this question! If you look into https://prettier.io/docs/en/configuration.html#configuration-overrides you will notice that you can do that by simply by updating you prettier configuration file. 

example of `~/.prettierrc`:

```json
{
  "overrides": [
    {
      "files": "*.md",
      "options": {
        "tabWidth": 4
      }
    }
  ]
}
```

Or you can add directly to the configuration of your project.

**Comment by mitermayer** [comment]
Closing this issue for now, but please feel free to re-open or comment in this issue in case the above does not solve your problem

**Comment by czosel** [comment]
Of course - thank you! :100:
