### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by mitermayer** [prettier/vim-prettier#126]
Creating this issue to track down users features / feedback that they would like to have done on `vim-prettier` 1.0. I will be creating a `1.x` branch where I will keep iterating towards the major release. Thing I will be tackling are:

* [x] finalizing async support for neovim (https://github.com/prettier/vim-prettier/issues/99)
* [x] Add configuration to use `default` prettier settings (we currently use default FB settings)
* [x] Add configuration preset support (allow users to select FB settings)
* [x] respect indentation of visually selected formatting (https://github.com/prettier/vim-prettier/pull/78)
* [x] backport segfault fix (https://github.com/prettier/vim-prettier/pull/138)
* [x] custom plugin support (https://github.com/prettier/vim-prettier/pull/120) with rebase on (https://github.com/prettier/vim-prettier/pull/155)
* [ ] Updated documentation on `vim-prettier` and on `prettier` for vim integration
* [ ] Add entry on the README explaining that we already support prettier configuration overwrites via files (.prettierrc,  prettier.config.js, etc..) and also on the project package.json
* [x] make `release/1.x` default git branch and move old "master" branch to `release/0.x` branch

Some stretch goals will be:

* [ ] adding support for different prettier CLI's (https://github.com/prettier/vim-prettier/issues/42 and https://github.com/prettier/vim-prettier/issues/20)
* [ ] Create a FAQ area 
* [ ] Errors that are not based on syntax should give user more information (maybe stacktrace)
* [ ] cleanup TODO's

* * *

If you guys have any suggestions of features or things you would like us to work on please leave a comment on this issue.

**Comment by sheerun** [comment]
Could you also support specifying prettier configuration in configuration file? https://prettier.io/docs/en/configuration.html Maybe even discovering prettier configuration by reading scripts in package.json

**Comment by mitermayer** [comment]
Hi @sheerun ,

This is already supported! you can already create a `.prettierrc` file on your home directory or project and `vim-prettier` will respect it. We should probably add this information to the README.md since this is not the first time that someone has similar questions around it

**Comment by docwhat** [comment]
@mitermayer Is there an issue for _Add configuration to use default prettier settings (we currently use default FB settings)_?

If there was an issue with a rough description of how you'd like things, I could start submitting PRs to help you out.  I've written a [wrapper](https://github.com/docwhat/dotfiles/blob/master/tag-nodejs/bin/prettier) to strip out `--no-editorconfig`, so this would be interesting to me.

**Comment by mitermayer** [comment]
Hi @docwhat , 

Been flooded with work this week will start working on it during the weekend. 

Please feel free to start submiting PR's, I think we can merge a lot quicker on the 1.0 branch and we can iterate on it until it get on a good stage for release.

**Comment by mitermayer** [comment]
Create the branch "release/1.x"

**Comment by chhschou** [comment]
How to enable .editorconfig support? Prettier supports it out of the box but vim-prettier does not respect it.

**Comment by mitermayer** [comment]
Hi @chhschou,

I have just created a issue to track that https://github.com/prettier/vim-prettier/issues/141, but the reason why did not support it on the past was due to a bug on prettier itself when using `.editorconfig` and `config-precedence` , I will investigate a bit more around it and add more information on the issue #141.

If that flag is no longer required I should be able to do a new `vim-prettier` release soon to cover it!

**Comment by mitermayer** [comment]
Hi @ELLIOTTCABLE,

Thanks for bringing that up! will definitely have a look into it!

**Comment by mitermayer** [comment]
I will resume working on vim-prettier in 2 weeks, been very busy at work at this stage as I am about to go on paternity leave in the next 2 weeks, I really appreciate you raising this issue

**Comment by ELLIOTTCABLE** [comment]
@mitermayer life before open source.

**Comment by fatso83** [comment]
I have tried adding a `.prettierignore` to projects to avoid formatting them, but this plugin seems to ignore that. That's quite unfortunate, so maybe something for 1.0?

**Comment by sandangel** [comment]
is that possible to use [prettier_d](https://github.com/josephfrazier/prettier_d) with `vim-prettier` ?

**Comment by sandangel** [comment]
and could you please help me with how to use fzf for quickfix with vim-prettier?

**Comment by CyrilAntoni** [comment]
Hi there,

Would it be possible to add the `close-empty-jsx-elements` option like in VS Code's Prettier?
https://github.com/prettier/prettier/issues/5442#issuecomment-437708682
So that `<div></div>` becomes `<div />`.

If I understand it well, the option should look like this:
`let g:prettier#config#close_empty_jsx_elements = 1`

Thanks!

**Comment by mitermayer** [comment]
Hi @CyrilAntoni,

Sure thing, do you want to create an issue to track that? I am happy to work on it during the weekend

**Comment by CyrilAntoni** [comment]
@mitermayer thank you that's very nice of you to do it, even on your weekend!

**Comment by mitermayer** [comment]
I acknowledge there are still some follow ups to be done for `release/1.x` but this branch has been open for way too long, I have also been dog-fooding this branch all throughout, so Then decided to merge it today to master.

Master is now set as version 1.0.0-alpha, will be listening to feedback and applying fixes/patches as needed and once stable will move it to `beta` and final release stages.

The older `master` version can still be accessible by `release/0.x` branch in case folks need for compatibility reasons
