### ISSUE TITLE
<Plug>(Prettier) doesn't work

### ISSUE THREAD

**Issue by huyvohcmc** [prettier/vim-prettier#132]
Follow the README, I added this line to my `init.vim`:
```
nnoremap <Leader>p <Plug>(Prettier)
```
But when I type my leader key follow by a `p` instantly, there are no prettier was run. It just pastes text (p) instead of fixing anything. If I change from `<Plug>(Prettier)` to `:Prettier`:
```
nnoremap <Leader>p :Prettier
```
Then it will actually work. Why?

neovim: 0.2.2
Prettier version: 0.2.6
Test file: regular javascript file
init.vim: https://github.com/huyvohcmc/dotfiles/blob/master/init.vim

**Comment by mitermayer** [comment]
Hi @huyvohcmc,

Thanks for raising this issue. Will investigate this a bit further I think in the meantime would you be open to submit a PR updating the README to your mappings ? also the `doc/prettier.txt` ? 

thanks :)

**Comment by huyvohcmc** [comment]
Did an update on vim plugins and restart my MacBook, everything seems to work as expected. But the problem is that they used to work before, hence the Vim configuration, then it doesn't work anymore. And just now, it is.

**Comment by mitermayer** [comment]
Hi @huyvohcmc,

> But the problem is that it used to work before, hence the Vim configuration, then it doesn't work anymore. And just now, it is.

Not sure I understood, so is it working or not now ?

Hoping to help find a solution for your problem

**Comment by huyvohcmc** [comment]
I mean I couldn't reproduce the issue anymore. Will close this one until I can reproduce it with clearer steps.
