### ISSUE TITLE
Why do the defaults differ?

### ISSUE THREAD

**Issue by larister** [prettier/vim-prettier#133]
**Do you want to request a *feature* or report a *bug*?**

Neither - just ask a question

**What is the current/expected behavior?**

The Readme.md states the following:

> Note: vim-prettier default settings differ from prettier intentionally.

However, there's no reasoning as to why. Is it just personal preference? If so, perhaps it's worth clarifying that in the Readme (happy to do this if you agree).

Additionally/alternatively, it might be good to have a `g:prettier#use_prettier_defaults` setting rather than having to override them manually.

Apologies if I've missed something here; I did try to check previous issues. Thanks so much for all your work on this, I love it!

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**

0.2.6

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**

1.11.1

**Comment by docwhat** [comment]
This will change in v1.0.0 — there is already some changes in this direction in the release/1.x branch.

**Comment by masaeedu** [comment]
@docwhat Are the settings listed in the README the comprehensive set that differs from default settings?

**Comment by docwhat** [comment]
I believe so. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
