### ISSUE TITLE
Re-enable .editorconfig support

### ISSUE THREAD

**Issue by mitermayer** [prettier/vim-prettier#141]
Prettier is .editorconfig compatible, but due to some incompatibility bugs in the past we had to deliberately disable that flag (https://github.com/prettier/vim-prettier/blob/master/autoload/prettier.vim#L327).

We should investigate if the issue is still applicable, otherwise we should remove that flag and do a new release.

**Comment by chhschou** [comment]
Thanks @mitermayer , I'll remove the `--no-editorconfig` flag locally and report back if I hit any snags.

**Comment by mitermayer** [comment]
Hi @chhschou,

I will try to look on this issue during the weekend. But this is definitly something we want to be fixed and working on `vim-prettier` and hopefully I can come up with a fix for it and do a release ASAP, will keep you posted by commenting on this issue

**Comment by oskarrough** [comment]
I tried removing `--no-editorconfig` locally where the plugin is installed and it seems to work. It respects editorconfig again.

My global `prettier` is 1.13.0.

**Comment by mitermayer** [comment]
Hi @oskarrough,

Thiss is great news, do you want to submit a PR for it ?

**Comment by chhschou** [comment]
I've updated to the latest vim-prettier but the `indent_size = 4` option still doesn't work for me. Does that work for you @oskarrough ?

**Comment by oskarrough** [comment]
Hi @chhschou, I just tried again and `indent_size` is respected here.

Not sure what it could be.. Did it update correctly? This line shouldn't be there: https://github.com/prettier/vim-prettier/pull/144/files. Which version of prettier are you using?

**Comment by chhschou** [comment]
Apologies I have a bit of issue with my setup. It is working for me now.
