### ISSUE TITLE
Adding support for lint tools custom executables after prettier (like lint-staged)

### ISSUE THREAD

**Issue by Industrial** [prettier/vim-prettier#148]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current/expected behavior?**
Prettier runs, conflicts with linting tools

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
0.2.7

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.14.2

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
/home/tom/Code/private_project/node_modules/.bin/prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**
No.

Hello. I love this tool, however as prettier conflicts with linting tools, those linting tools' configurations should be leading in how the document is formatted, because the linting tools are integrated into CI tools etc.
Using the npm package `lint-staged` We are able to configure the linting tools to run after prettier:

```
  "lint-staged": {
    "./**/*.{js,jsx,json}": [
      "prettier --write",
      "eslint --fix",
      "git add"
    ]
  }
```

I would like to request this kind of functionality in `vim-prettier`, such that I can configure the command to run and so have multiple tools ran at that time.

**Comment by mitermayer** [comment]
Thanks for raising this issue, I will resume working on vim-prettier in 2 weeks, been very busy at work at this stage as I am about to go on paternity leave in the next 2 weeks, I really appreciate you raising this issue

**Comment by mitermayer** [comment]
Looks like this PR is to add support to "lint-staged" executable, will fall in the same category of issues https://github.com/prettier/vim-prettier/issues/42 and https://github.com/prettier/vim-prettier/issues/20 which wants to have support for other executables.

**Comment by mitermayer** [comment]
Unfortunately at this stage I can commit to this issue, it has been already tricky to ensure we are always working with `prettier` cli upstream let alone start adding new dependencies. 

If this feature is highly desirable i suggest looking into Ale
