### ISSUE TITLE
styling over scp

### ISSUE THREAD

**Issue by ThomasGHenry** [prettier/vim-prettier#149]
**Do you want to request a *feature* or report a *bug*?**
Not sure. Feature, probably.

**What is the current/expected behavior?**
When I open a remote file over scp (vim scp://user@host//path/to/remote/file ), vim creates some sort of tmp buffer to work from and prettier doesn't know where the actual file is to perform its task. Is it possible to configure prettier to look at the current buffer, and not choke on the scp path? Or is this beyond configuration?

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
0.2.7

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.14.0

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**
didn't try

Thanks!

**Comment by mitermayer** [comment]
I never tried this, will look into it! Its definietly something worth supporting if possible

**Comment by mitermayer** [comment]
Will try to investigate this issue as it seems like a super useful feature to support

**Comment by mitermayer** [comment]
Haven't had time to look into this. Will close this issue for now but have added it to a list of "wish" lists for the future, and when time comes will reopen it.
