### ISSUE TITLE
Unexpected cursor movement

### ISSUE THREAD

**Issue by peteyycz** [prettier/vim-prettier#151]
I'd like to report a bug.

Current Behaviour:
When I enable async autoformatter on save, and save the file, the cursor jumps to the end of the file.

Expected behavior:
It should not move my cursor.

PrettierVersion: 0.2.7
PrettierCliVersion: 1.14.2
PrettierCliPath: project local/.bin/prettier

**Comment by mitermayer** [comment]
Sorry for the delay, will try to look into this now and see if I can reproduce

**Comment by mitermayer** [comment]
Could you provide me a bit more info in order for me to debug this issue ? 

What "OS" are you using ?

Could you also please paste the stdout of your "vim --version" ?

Thanks a lot!

**Comment by mitermayer** [comment]
I haven't managed to replicate this issue or seen any other report around it. Happy to reopen when having more steps to reproduce this
