### ISSUE TITLE
`E121: Undefined variable: g:prettier#autoformat` when executing `vi`

### ISSUE THREAD

**Issue by hankchiutw** [prettier/vim-prettier#161]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current/expected behavior?**
current:
Whenever I edit a js file, I get the error like:
```
Hankde-MacBook-Pro:src hankchiu$ vi index.js
Error detected while processing /Users/hankchiu/.vim/bundle/vim-prettier/ftplugin/javascript.vim:
line    3:
E121: Undefined variable: g:prettier#autoformat
E15: Invalid expression: g:prettier#autoformat
Press ENTER or type command to continue
```
expected:
Open `vi` without error.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
0.2.7

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.15.1

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
/usr/local/bin/prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**
vim-prettier
@
I'm not familiar of writing *.vim file, but if I change the file `vim-prettier/ftplugin/javascript.vim` line 3 like:
```
- if g:prettier#autoformat
+ if exists('g:prettier#autoformat')
```
then I can execute `vi` normally.

Is this a bug or something else obviously I should do before using vim-prettier?

#

**Comment by mitermayer** [comment]
Hi @hankchiutw 

I will look into this sometime tonight! Thank you for reporting this issue. What is the output of your `vim --version` ?

**Comment by hankchiutw** [comment]
Thanks, @mitermayer ! Here you are:
```
Hankde-MacBook-Pro:code hankchiu$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)
Included patches: 1-898, 8056
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             -farsi           -mouse_netterm   +syntax
-arabic          +file_in_path    -mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           -mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
+builtin_terms   -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    -keymap          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             -rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
-emacs_tags      -mouseshape      -sniff           -xsmp
+eval            -mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv
```

**Comment by mitermayer** [comment]
Hi @hankchiutw 

Do you have any custom vim-prettier configuration on your `.vimrc` file ??

**Comment by mitermayer** [comment]
Hi @hankchiutw 

Are you sure you have the correct `vim-prettier` installed ? That file that you mentioned does not have that line 

https://github.com/prettier/vim-prettier/blob/f2755ec6fe465fb6af051a254d826018dcde2a50/ftplugin/javascript.vim#L1

**Comment by hankchiutw** [comment]
Finally, I found it's related to my `.vimrc`.
A small `.vimrc` to make this issue happen is:
```
execute pathogen#infect()
filetype plugin on
filetype detect
```

**Comment by mitermayer** [comment]
Will close this issue for now as other users have not mentioned to have this problem as well, feel free to reopen if anyone face the same issue

**Comment by hankchiutw** [comment]
I found that `plugin` is loaded after `ftplugin`([ftplugin-overrule](http://vimdoc.sourceforge.net/htmldoc/filetype.html#ftplugin-overrule)).

This may be the root cause of the issue. But I don't know clearly why it happens only when using `vim-pathogen`.

@mitermayer , I created a PR(https://github.com/prettier/vim-prettier/pull/217), could you have a look? thanks!
