### ISSUE TITLE
Document how to add custom extensions

### ISSUE THREAD

**Issue by bserem** [prettier/vim-prettier#167]
**Do you want to request a *feature* or report a *bug*?**
Documendation update / Missing documendation
**What is the current/expected behavior?**
Vim-Prettier runs fine on files it can understand (css, scss, php with the plugin).
What I am missing is how to map it to other file extensions.
For example:
Drupal uses `.module` and `.theme` extensions, which are PHP files. I would love to have Vim-Prettier work on them.

Document that this is possible with the following config:
```
autocmd FileType module let b:prettier_ft_default_args = {
  \ 'parser': 'php',
  \ }
```

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
`0.2.0`
**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
`1.15.3`
**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
`prettier`
**Did this work in previous versions of vim-prettier and/or prettier ?**
Irrelevant

**Comment by mitermayer** [comment]
On release/1.x this should work just by ensuring the plugin is installed

**Comment by mitermayer** [comment]
Plugins are enable by default, closing this issue for now.
