### ISSUE TITLE
Document how to add q-args

### ISSUE THREAD

**Issue by 1ak31sha** [prettier/vim-prettier#168]
Could you please add documentation for examples of `<q-args>`? I cant seem to figure out how to pass `--tab-width 2` for example. Thank you!

**Comment by mitermayer** [comment]
Hi @1ak31sha I will do that, in the meantime you can pass `<q-args>` using `:PrettierCli <q-args>` that wont include any of the defaults of `vim-prettier` so you would have to construct the the command yourself. 

It may make sense to have `:PrettierCli` allow the extra `<q-args>` to overwrite the defaults, if you think this is a good idea I may be able to create a feature task for it on the `release-1.x` branch

**Comment by 1ak31sha** [comment]
Thanks @mitermayer ! I'd be happy to even help with adding the docs. But still not sure how to use <q-args> . maybe it is obvious but i cant seem to get it to work. ive tried `:PrettierCli --tab-width 2` and :PrettierCli '--tab-width 2'`

**Comment by mitermayer** [comment]
Closing this for now. We are working on new docs that should address this issue
