### ISSUE TITLE
Support prettier/prettier-ruby

### ISSUE THREAD

**Issue by awinograd** [prettier/vim-prettier#172]
**Do you want to request a *feature* or report a *bug*?**

feature

https://github.com/prettier/plugin-ruby was just released, is it possible to add support for it in vim-prettier?

I tried digging through the source to add the a `--plugin` option which I thought would be necessary but my vimscript skills are lacking. Please let me know if I can help.

**Comment by awinograd** [comment]
Duplicate of https://github.com/prettier/vim-prettier/issues/167

**Comment by mitermayer** [comment]
On release/1.x all that is needed should be to add it to the package.json file, I believe that we no longer need to pass `parser` as part of the config as it is currently inferred by --stdin-filepath.  

I will add prettier/prettier-ruby to the shipped deps on release/1.x
