### ISSUE TITLE
on run :Prettier command weird characters added at the beginning of the file

### ISSUE THREAD

**Issue by tehdb** [prettier/vim-prettier#174]
"^[[5 q" added to the beginning of the file:

![2019-02-13 18 36 05](https://user-images.githubusercontent.com/3496336/52731747-cbbd8e00-2fbe-11e9-8e4b-5fff883fff44.gif)

**Comment by tehdb** [comment]
the problem was [this snippet to change the cursor style](https://unix.stackexchange.com/questions/433273/changing-cursor-style-based-on-mode-in-both-zsh-and-vim/433321) in my .zshrc, has nothing to do with vim-prettier, going to close the issue

**Comment by bishaludas** [comment]
i my case running prettier was add `>4;m[>4;2m` syntax in place of cursor.
Fixed it by adding below lines in my .vimrc
```
let &t_TI = ""
let &t_TE = ""
```
