### ISSUE TITLE
add groovy handling

### ISSUE THREAD

**Issue by panjacek** [prettier/vim-prettier#177]
Could we get a groovy scripts handling?

It's a language used by jenkins to describe pipelines.

**Comment by mitermayer** [comment]
Hi @panjacek ,

I would love to have support for groovy one day! But in order for us to be able to support groovy we would need a groovy plugin (parser/printer) to be implemented for prettier. 

Please refer to:

* supported official convertions:  https://prettier.io/docs/en/index.html 
* official supported plugins: https://github.com/prettier

If you know of a prettier groovy pluggin please feel free to reopen this issue
