### ISSUE TITLE
Calling Prettier error if project contains prettier configuration

### ISSUE THREAD

**Issue by shuLhan** [prettier/vim-prettier#178]
This issue describe the problem that the pull request #160 want to fix.

**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current/expected behavior?**

Prettier does not format AngularJS HTML file.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**

* master at  2019-02-18 be14f94
* release/1.x 2019-02-18 cb598c1

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**

1.15.3

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**

(redacted)/node_modules/.bin/prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**

No.

## Problem (Steps to reproduce)

I have an AngularJS template with an extension `.tmpl`.  To detect the extension as HTML I add `${VIM}/ftdetect/tmpl.vim`,

```
au BufRead,BufNewFile *.tmpl set filetype=html
```

My .vimrc config with vim-prettier,

```
let g:prettier#autoformat = 0

autocmd BufWritePre *.html,*.tmpl,*.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.vue Prettier
```
In the project root directory, I have configured prettier in package.json,

```
...
	"prettier": {
		"useTabs": true,
		"tabWidth": 4,
		"semi": true,
		"trailingComma": "es5"
	},
...
```

Now, if I create the "test.tmpl" with the following content (intentionally un-formatted),

```
<a href="#" class="skip">
	<strong ng-click="$ctrl.onCloseBanner()" ng-bind="::$root.t.SKIP"></strong>
		</a>
```

and save it should be formatted, at least, into,

```
<a href="#" class="skip">
	<strong ng-click="$ctrl.onCloseBanner()" ng-bind="::$root.t.SKIP"></strong>
</a>
```

but its not formatted. If I call `:Prettier` directly it will print an error `Prettier: failed to parse buffer.`.

## Solutions

There are two solution for this: first is permanent fix in PR #160; and another is temporary fix by adding the following vim-prettier config into `.vimrc`,

```
let g:prettier#config#config_precedence = 'file-override'
```

I hope that explain the problem and the background of PR #160.

**Comment by mitermayer** [comment]
Hi @shuLhan ,

Thanks for the detailed explanation! I am happy to merge your PR for changing the default to 'file-override' on the `release/1.x` branch. Would you mind updating your PR to point to that release instead ?

**Comment by shuLhan** [comment]
Done.

**Comment by mitermayer** [comment]
Hi @shuLhan,

Looks like the PR still pointing to the master branch, Do you mind double check it ?

**Comment by mitermayer** [comment]
Merged to ‘release/1.x’

**Comment by alexventuraio** [comment]
I had the same problem but I do confirm that cloning `release/1.x` for **pathogen**, worked for me like a charm!
👏🏻😎
