### ISSUE TITLE
Error detected while processing BufWrite Auto commands for "*.rb"

### ISSUE THREAD

**Issue by eibrahim** [prettier/vim-prettier#180]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current/expected behavior?**
When I try to pretty ruby files, i get 
```
Error detected while processing BufWrite Auto commands for "*.rb":
```
**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
0.2.7
**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.16.4
**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
/Users/emad/.vim/bundle/vim-prettier/node_modules/.bin/prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**
N/A

**Comment by mitermayer** [comment]
Hi @eibrahim the master branch has no support for `ruby` plugins yet. If you want to try using prettier with ruby support you can use our `release/1.x` branch in the meantime. Hopefuly soon we will be doing a release.

an example on how to use the `release/1.x` branch is : 


```vim
Plug 'prettier/vim-prettier', {
  \ 'do': 'yarn install',
  \ 'branch': 'release/1.x',
  \ 'for': [
    \ 'javascript',
    \ 'typescript',
    \ 'css',
    \ 'less',
    \ 'scss',
    \ 'json',
    \ 'graphql',
    \ 'markdown',
    \ 'vue',
    \ 'lua',
    \ 'php',
    \ 'python',
    \ 'ruby',
    \ 'html',
    \ 'swift' ] }
```
