### ISSUE TITLE
No syntax color for html files when vim-prettier is enabled

### ISSUE THREAD

**Issue by Fandekasp** [prettier/vim-prettier#183]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current/expected behavior?**
file syntax coloration should behave independently from plugins like vim-prettier.

vim-prettier enabled
![](https://i.imgur.com/9tQaCLv.png)

vim-prettier disabled
![](https://i.imgur.com/0ABk4TN.png)

* disabling the 3 lines is the only thing I changed in my vimrc.
* Auto-selection of htmldjango filetype over html is done by plugin 'tweekmonster/django-plus.vim'
* As you can see  in the screenshot, html/htmldjango filetypes aren't evne listed in the vim-prettier Plug for list. Therefore I cannot run `:PrettierVersion` from that file

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
when run from a js file, I get `0.2.7`

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
```
node: error while loading shared libraries: libicui18n.so.63: cannot open shared object file: No such file or directory^@
```
⇒ Well, maybe that's the reason of the problem, although I'd love to understand the reason for the libicui18n library to break filetype selection when vim-prettier is on.

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
/home/dori/.vim/plugged/vim-prettier/node_modules/.bin/prettier

**vimrc**
```vim
Plug 'prettier/vim-prettier', {
           \ 'do': 'yarn install',
           \ 'for': ['javascript', 'typescript', 'typescript.tsx', 'json', 'yaml', 'markdown'] }  " JS
Plug 'tweekmonster/django-plus.vim', { 'for': ['python', 'htmldjango', 'html'] }
```

**Comment by Fandekasp** [comment]
Tried a quickfix with
```console
$ sudo ln -s /usr/lib/libicui18n.so /usr/lib/libicui18n.so.63
$ sudo ln -s /usr/lib/libicuuc.so /usr/lib/libicuuc.so.63
```

but it's getting uglier

```
:PrettierCliVersion
node: symbol lookup error: node: undefined symbol: _ZN6icu_638ByteSink15GetAppendBufferEiiPciPi^
```

**Comment by Fandekasp** [comment]
@junegunn @tweekmonster any idea why this is happening? How can I debug this?
Thanks for your help

**Comment by Fandekasp** [comment]
@mitermayer sorry, I have never used vim-prettier in the end, and am not working on a js project at the moment. But I'll keep in mind that you release a new version for the next opportunity, thanks!

**Comment by mitermayer** [comment]
Hi @Fandekasp,

Thanks for letting me know. Will close this issue :) feel free to re-open in the future if you still experience this issue
