### ISSUE TITLE
formatting by saving works only for languages of last opened file

### ISSUE THREAD

**Issue by 0xnoob** [prettier/vim-prettier#185]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current/expected behavior?**

**current**
When I open file(s) in programming language X and then another file in language Y (with `:tabnew`), auto formatting on save doesn't work anymore for files in programming language X.

e.g.

1. I open up an html-file, then in a new tab a js-file: format on save doesn't work for the html-file anymore.
2. Then I open up  a css-file in a new tab: format on save doesn't work for the html- & js-file anymore.
3. I open up another js-file in a new tab: format on save doesn't work for the html and css file, but works for **both** js-files.

All files have a `@format` pragma annotation.
Only Format on auto-save is affected, formatting with `:Prettier` works for all languages/files.

**expected**
Format on auto-save should work for all languages/files.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
**0.2.7**

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
**1.17.0^@**

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
**prettier**

**Did this work in previous versions of vim-prettier and/or prettier ?**
Don't know.

---
Same behavior with the local executable  (~/vim/plugged/vim-prettier/node_modules/.bin/prettier - same version: 1.17.0^@).

Same behavior in neovim (v0.3.4) and vim(v8.1).

My init.vim only contains the Plugin, no additional Configuration for vim-prettier:

`Plug 'prettier/vim-prettier', { 'do': 'yarn install' }`

I also added all the languages manually (e.g. `'for': [ 'html', css', 'javascript']`), but the behavior didn't change.

**Comment by 0xnoob** [comment]
Now auto formatting on save never works. :worried:  
Even if I only have a single file   open, the file does contain a `// @format` annotation, but it still works via `:Prettier`.

Adding `let g:prettier#autoformat = 1` to my `.vimrc` doesn't fix it either.

---
Just to be sure it's the right version I'm testing:

```
➜ <.vim/plugged/vim-prettier/package.json
{
  "name": "vim-prettier",
  "author": "Mitermayer Reis <mitermayer.reis@gmail.com>",
  "version": "1.0.0-alpha",
  [...]
}
```

**Comment by mitermayer** [comment]
Hi @0xnoob 

Thanks for reporting this, looks like a regression in the `release/1.x` branch. Will work on fixing this issue ASAP.

it looks like we are not adding the commands for that branch, the command on master is https://github.com/prettier/vim-prettier/blob/master/ftplugin/javascript.vim and on release/1.x branch is https://github.com/prettier/vim-prettier/tree/release/1.x/ftplugin

**Comment by mitermayer** [comment]
Will look into this, hopefully should be able to have a diff for it sometime soon prob around the weekend

**Comment by mitermayer** [comment]
In the meantime to unblock you do you want to manuall configure `vim-prettier` to run on auto-save by updating your `.vimrc` settings ?

Copying bellow reference from the README.md in here:

To enable vim-prettier to run in files without requiring the "@format" doc tag.
First disable the default autoformat, then update to your own custom behaviour

Running before saving sync:

```vim
let g:prettier#autoformat = 0
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html Prettier
```

Running before saving async (vim 8+):

```vim
let g:prettier#autoformat = 0
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync
```

Running before saving, changing text or leaving insert mode:

```vim
" when running at every change you may want to disable quickfix
let g:prettier#quickfix_enabled = 0

let g:prettier#autoformat = 0
autocmd BufWritePre,TextChanged,InsertLeave *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync
```

**Comment by mitermayer** [comment]
I no longer can reproduce this issue, feel free to reopen if this still happens

**Comment by phinjensen** [comment]
This bug is happening for me with window splitting, exactly as @0xnoob described. Output of `:PrettierVersion` is `1.0.0-alpha`, and I ran `:PlugUpdate` to make sure everything was up to date.

**Comment by mattsoftware** [comment]
I have same issue as @0xnoob , updated to latest vim-prettier (was on an older commit) after the files were sometimes not auto formatting. It would seem to work for a while then stop. The older commit was 427ef6830294c722f04cd3799f2c27a6629976a6 which seems to work well for me.

After updating to the lastest master, auto formatting just stopped completely. I couldn't figure out how to resolve it so went back to the previous commit and its working for me again ¯\_(ツ)_/¯

**Comment by johanventer** [comment]
@mitermayer, tagging you on a closed issue because it still exists in latest version for me. 

So here's the problem.

Lets say I open a Typescript file, the following `BufWritePre` exists:
```
:autocmd BufWritePre
--- Autocommands ---
Prettier  BufWritePre
    *.ts      call prettier#Autoformat()
    *.tsx     call prettier#Autoformat()
```

If I then split and open a JSON file, `BufWritePre` is overridden:
```
:autocmd BufWritePre
--- Autocommands ---
Prettier  BufWritePre
    *.json    call prettier#Autoformat()
```

If you `:e` on the file, then `BufWritePre` is set to what it should be.

This is because each file in `ftplugin` is blowing away the `Prettier` `augroup`, ie `ftplugin/typescript.vim`:
```
augroup Prettier
  autocmd!
  autocmd BufWritePre *.ts,*.tsx call prettier#Autoformat()
augroup end
```

The main `plugin/prettier.vim` actually sets this group up for all supported filetypes:
```
augroup Prettier
  autocmd!
  autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html noautocmd | call prettier#Autoformat()
augroup end
```

So the simple solution is to remove the `augroup Prettier` in each file in `ftplugin` and the flip flopping between working and broken auto formatting stops.

**Comment by mitermayer** [comment]
Please feel free to submit a PR and I can test it and merge it
