### ISSUE TITLE
fail to parse buffer?

### ISSUE THREAD

**Issue by tornoda** [prettier/vim-prettier#187]
**I have checkout all the issues without no answer to my problem**
I only do one thing in my .vimrc file:
Plug 'prettier/vim-prettier', {'do': 'yarn install'}

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current/expected behavior?**
fail to parse buffer
**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
0.2.7
**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.17.0
**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
/home/{myname}/.vim/plugged/vim-prettier/node_modules/.bin/prettier
**Did this work in previous versions of vim-prettier and/or prettier ?**
I don't know, I am a beginner of vim and vim-prettier

**Comment by CyrilAntoni** [comment]
Hello there,
I installed vim-prettier yesterday and it was working for some time. But now it displays this error in Vim:
```
Prettier: no prettier executable installation found 
```

I use vim-plug, npm and the latest release/1.x branch.

Here is my `.vimrc`:
```
" Auto Install Vim-Plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
" Plugins
call plug#begin('~/.vim/plugged')

Plug 'prettier/vim-prettier', {
  \ 'do': 'npm install',
  \ 'branch': 'release/1.x',
  \ 'for': [
    \ 'javascript',
    \ 'typescript',
    \ 'css',
    \ 'less',
    \ 'scss',
    \ 'json',
    \ 'graphql',
    \ 'markdown',
    \ 'vue',
    \ 'lua',
    \ 'php',
    \ 'python',
    \ 'ruby',
    \ 'html',
    \ 'swift' ] }
Plug 'airblade/vim-gitgutter'
Plug 'itchyny/lightline.vim'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'mattn/emmet-vim'
Plug 'scrooloose/nerdtree'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-surround'
Plug 'w0rp/ale'
Plug 'tomtom/tcomment_vim'
Plug 'ap/vim-css-color'
Plug 'mxw/vim-jsx'
Plug 'jeffkreeftmeijer/vim-numbertoggle'

call plug#end()
" Source the Plugins.vim file
" so ~/.vim/plugins.vim

" Prettier Auto-Fromat On Save
" when running at every change you may want to disable quickfix
let g:prettier#quickfix_enabled = 0
let g:prettier#autoformat = 0
autocmd BufWritePre,TextChanged,InsertLeave *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync

" Open NERDTree Automatically When Vim Start Up
autocmd vimenter * NERDTree
" NERDTree Show Hidden Files
let NERDTreeShowHidden=1

" Set Tab to 2 Spaces
filetype plugin indent on
" show existing tab with 2 spaces width
set tabstop=2
" when indenting with '>', use 2 spaces width
set shiftwidth=2
" On pressing tab, insert 2 spaces
set expandtab

" Redifine Emmet Default Expansion Shortcut
let g:user_emmet_leader_key='<C-Z>'

" Activate Relative Line Numbering
set number relativenumber
 
" FZF Fuzzy Search
map ; :Files<CR>

```
I saved it `:w`, sourced it `:source %` and installed it `:PlugInstall`.
I even tried to restart my computer and to update it `:PlugUpdate` but to no avail.

When I do `npm i` in the `~/.vim/plugged/vim-prettier` directory I get this error:
```
~/.vim/plugged/vim-prettier$ npm i
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN checkPermissions Missing write access to /home/cyril/.vim/plugged/vim-prettier
npm ERR! path /home/cyril/.vim/plugged/vim-prettier
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/home/cyril/.vim/plugged/vim-prettier'
npm ERR!  [Error: EACCES: permission denied, access '/home/cyril/.vim/plugged/vim-prettier'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/home/cyril/.vim/plugged/vim-prettier'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/cyril/.vim/plugged/vim-prettier'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cyril/.npm/_logs/2019-08-28T14_10_03_629Z-debug.log

```

@mitermayer Do you think it's linked to the deprecated dependencies?

**Comment by mitermayer** [comment]
Hi @CyrilAntoni,

From your stacktrace error above looks like your computer is having permission problems with that directory. Please note this lines:

```
npm ERR! Error: EACCES: permission denied, access '/home/cyril/.vim/plugged/vim-prettier'
npm ERR!  [Error: EACCES: permission denied, access '/home/cyril/.vim/plugged/vim-prettier'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/home/cyril/.vim/plugged/vim-prettier'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/cyril/.vim/plugged/vim-prettier'
npm ERR! }
```

can you manually perform this steps to test it out ?

1. got to `/home/cyril/.vim/plugged/vim-prettier`
2. do a pull by `git pull`
3. remove existing node_modules `rm -rf /home/cyril/.vim/plugged/vim-prettier/node_modules`
4. install deps again `(cd /home/cyril/.vim/plugged/vim-prettier/node_modules && npm install)`

Please let me know how does the above goes

**Comment by mitermayer** [comment]
Could you please paste the output of `ls -alh /home/cyril/.vim/plugged/vim-prettier` ? I It looks like directory permission issues:

```
npm WARN checkPermissions Missing write access to /home/cyril/.vim/plugged/vim-prettier
```

Another thing worth trying to fix your directory permissions for `vim-prettier` installation like so:

`sudo chown -R $USER:$USER /home/cyril/.vim/plugged/vim-prettier` that should fix directory permissions for you.

**Comment by CyrilAntoni** [comment]
@mitermayer that was it! I probably ran a `sudo` at some point and all my files belonged to the root user:
```
total 56
4 drwxr-xr-x 12 root root 4096 août  28 15:24 ale
4 drwxr-xr-x  8 root root 4096 août  28 15:24 emmet-vim
4 drwxr-xr-x 11 root root 4096 août  28 15:24 fzf
4 drwxr-xr-x  8 root root 4096 août  28 15:24 fzf.vim
4 drwxr-xr-x  7 root root 4096 août  28 15:24 lightline.vim
4 drwxr-xr-x 10 root root 4096 août  28 15:24 nerdtree
4 drwxr-xr-x  8 root root 4096 août  28 15:24 tcomment_vim
4 drwxr-xr-x  7 root root 4096 août  28 15:24 vim-css-color
4 drwxr-xr-x  8 root root 4096 août  28 15:24 vim-gitgutter
4 drwxr-xr-x  5 root root 4096 août  28 15:24 vim-jsx
4 drwxr-xr-x  8 root root 4096 août  28 15:24 vim-multiple-cursors
4 drwxr-xr-x  5 root root 4096 août  28 15:24 vim-numbertoggle
4 drwxr-xr-x 11 root root 4096 août  28 15:24 vim-prettier
4 drwxr-xr-x  5 root root 4096 août  28 15:24 vim-surround
```
So I ran the `sudo chown -R $USER:$USER /home/cyril/.vim` you indicated (on the .vim directory to make sure) and then `npm i` in the vim-prettier directory.

The plugin now works perfectly, thank you for the quick and well explained answer!

**Comment by CyrilAntoni** [comment]
I also noticed that Prettier was failing to parse buffers when attempting to run it from `sudo vim` (launched from a bash script).
So if you have issues it may be worth checking if running `vim` works better than `sudo vim`.

**Comment by mitermayer** [comment]
@CyrilAntoni ,

If you run using `sudo vim` vim will run as the user `root` which it may not have access to `prettier` CLI on its path and possibly no access to the vim plugins as its `$HOME` directory would not match your directory, it would be on `/home/root`, also it means when you save any file it will change the permissions of saved file to `root:root` which will mean you wont be able to edit/modify that file as a normal user.

**Comment by mitermayer** [comment]
Closing this issue as it seems to have been solved, feel free to re-open if still experiencing any issues
