### ISSUE TITLE
Failed to parse buffer import.meta.url

### ISSUE THREAD

**Issue by radical-edo** [prettier/vim-prettier#188]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current/expected behavior?**
Current:
Getting error `"Prettier: faliled to parse buffer."` when I'm in `.mjs` file and using `import.meta.url` to get the `__dirname` equivalent for ESM modules in `Node.js`

Expected:
No error

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
0.2.7
**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.17.0
**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**
Works in Prettier I've checked on [prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOEA2cB0mIDmAFADpQAE5AlgLYAOEATjDjXDAIY4CujmZAShAAaEBDowq6ZKA6NGEAO4AFOQjTIQHAG4QqAExEgARow5gA1uwDKdc1SgFkMRtziiAFjBqYA6h6p4NDswOGt1QKptQIBPTTA0DVEHNDhmZTMCGg5kADMOTFTRACs0AA8AITNLGw42ABkHODyCopBSsusHAmwARW4IeBbC9xA7RlTGTWMOYxj8KCM6RgcYXwMYD2QADgAGUWWIVN8zOk1luEntZtEARwH4DPENFA40AFooODh9H6NGOD3KgAjIcLI5JD5EaiVI0KjOVyjNDdPoPZqQ1qjTjGdb6TbIABMohcHComG6AGEIDRspooNAbiBuKkACqzF5Q1IAXy5QA)

No idea about the previous version, though

**Comment by mitermayer** [comment]
I no longer can reproduce this issue, feel free to reopen if this still happens
