### ISSUE TITLE
.prettierignore appends a bunch of nonsense

### ISSUE THREAD

**Issue by lpender** [prettier/vim-prettier#189]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current/expected behavior?**

Steps to Reproduce:

1. Create a `.prettierignore` file in the root of a directory, with the contents: `**/*`.
2. Create a file `test.js`. with the contents: 

```
function test() {
  console.log('test');
}
```
3. Save that file

**Expected Result**

Nothing should happen

**Actual Result**

It saves the file with the contents:

```
function() test {
  console.log("test");
} console.log("test");}ole.log("test");}
```

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
```
0.2.7
```

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**

```
1.13.4
```

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**

```
/Users/lpender/.vim/bundle/vim-prettier/node_modules/.bin/prettier
```

**Did this work in previous versions of vim-prettier and/or prettier ?**

I don't know.

**Comment by jparr721** [comment]
Same happens to me actually, but it just copies the bottom two lines of the file on save. This happens for me primarily with json and .js files.

**Comment by mitermayer** [comment]
I no longer can reproduce this issue, feel free to reopen if this still happens
