### ISSUE TITLE
Window is unexpectedly scrolled after :Prettier

### ISSUE THREAD

**Issue by GeneZharov** [prettier/vim-prettier#192]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current/expected behavior?**
Steps to reproduce:
1. Open any JavaScript file that is big enough to be vertically scrollable.
3. Add an empty line to the end of a buffer. (actually, other edits also cause this issue but new lines at the ending are easier to reproduce)
3. Set the cursor position at the last (empty) line.
2. `:vs`
4. `:PrettierAsync` or `:Prettier`
5. Inactive window to the right will be scrolled to the very bottom so that there will be only one visible line of code on the screen (see the screenshot).

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
0.2.7
Actually, a similar issue occurs in the 'release/1.x'. A cursor in an inactive window jumps to the beginning of the buffer. 

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.17.1

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
/home/user/p/introversion/node_modules/.bin/prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**
It never worked properly in my experience.

```
:ver
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0/x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DMIN_LOG_LEVEL=3 -Wall -
Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE
_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_UNIBI_HAS_VAR_FROM -I/var/tmp/portage/app-editors/neovim-0.3.1/work/neovim-0.3.1_build/config -I/var/tmp/portage/app-editors/neovim
-0.3.1/work/neovim-0.3.1/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.3.1/work/neovim-0.3.1_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.3.1/work/n
eovim-0.3.1_build/include
Compiled by root@cuckoo

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

![screenshot_15:44_2019-07-16-label](https://user-images.githubusercontent.com/12275402/61300208-3aab4700-a7ea-11e9-8d17-7445f775601b.png)

**Comment by svengiebel** [comment]
Hey @mitermayer im using `release/1.x` but i still got the same problem :(
Does not happen always though...

**Comment by GeneZharov** [comment]
I solved it this way:

```
let g:ale_fixers = {
\  'javascript': ['prettier'],
\  'json': ['prettier'],
\  'css': ['prettier'],
\  'scss': ['prettier'],
\  'html': ['prettier'],
\  'xml': ['prettier'],
\}

let g:ale_fix_on_save = 1
```

It is [ALE](https://github.com/dense-analysis/ale) for those who didn't catch the joke. Another plugin that is capable of running prettier.

**Comment by svengiebel** [comment]
Did the same with coc.nvim :)

**Comment by mitermayer** [comment]
Closing this issue for now, did some fixes on `release/1.x` if anyone still experience this issue on `release/1.x` i will then re-open

**Comment by francium** [comment]
Seeing this happen on commit aa0607 (latest develop at time of writing).
My steps are roughtly
1. Open two files in vertical splits, both in my case are long enough to be scrollable
2. Edit both files' formatting as to trigger prettier on save
3. Save, non-focused split regularly (not always) scrolls to the very as -- identical to the screenshot attached by @GeneZharov above.

I've commented out everything in my config except this,
```
function! LoadPlugins()
    call plug#begin()
 
    Plug 'prettier/vim-prettier', {
        \ 'do': 'yarn install',
        \ 'for': ['javascript', 'typescript'] }
        let g:prettier#autoformat = 1
        nmap <leader>ap :Prettier<CR>
 
 
    call plug#end()
endfunction
 
call LoadPlugins()
```

NVIM v0.5.0-dev
