### ISSUE TITLE
make prettier respect eslint

### ISSUE THREAD

**Issue by aranmohyeddin** [prettier/vim-prettier#194]
How to configure prettier to use eslint --fix or be compatible with the eslint config of the project?

For example in my vue files eslint turns:
```
<script>
var a;
</script>
```
into this:
```
<script>
  var a;
</script>
```
And that is incompatible with my eslint configurations.

**Comment by niksubramanian** [comment]
I'm having the same issue with Vue: any insights on how you managed to fix this @aranmohyeddin ?

Thanks in advance!

**Comment by aranmohyeddin** [comment]
I couldn't manage...
