### ISSUE TITLE
Loading global .prettierrc from user's home ?

### ISSUE THREAD

**Issue by playahater** [prettier/vim-prettier#197]
Hey guys,

Quick question. Any way to load the .prettierrc from the user's home dir when it's not found in project dir ?
Like loading a global ~/.prettierrc by default ?

Can't seem to find a way to do this.
Any feedback is more than appreciated in advance,

Milos

**Comment by playahater** [comment]
Hi @mitermayer 

Thank you for your feedback.

So i'm using Vim 8.1.1906 on Archlinux.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
1.0.0-alpha

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.18.2

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
prettier [ full exported path is ~/.node/bin/prettier ]

relevant prettier lines from my .vimrc:
```
Plug 'prettier/vim-prettier', { 'do': 'npm install -g', 'branch': 'release/1.x', 'for': [ 'javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'lua', 'php', 'python', 'ruby', 'html', 'swift' ] }
let g:prettier#autoformat = 0                                                   
let g:prettier#quickfix_enabled = 0                                             
let g:prettier#exec_cmd_async = 1
au BufRead,BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync
```
As far as i see, config_precedence is file-override by default so i didn't add this in my vimrc.

And this is the .prettierrc file:

```
{
  "printWidth": 170,
  "tabWidth": 4,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "none",
  "jsxBracketSameLine": true,
  "bracketSpacing": true,
  "overrides": [{
    "files": "*.php",
      "options": {
        "braceStyle": "1tbs"
   }
  }],
}
```


When i copy ~/.prettierrc to a project document root, it works correctly.
When i remove from the project document root and leave only the one in home, it doesn't; it uses the default preset set by vim-prettier.

If this behavior is not the result of false configuration on my end maybe i can give it a shot with debugging the core issue.
Not much experience with vim plugins, but if you give me some kind of pointer of where can i start with debugging, perhaps i can give it a shot. Maybe autoload/prettier/resolver/config.vim as a starting point ?

Thank you in advance

**Comment by playahater** [comment]
hey @mitermayer 

Sorry for delay. 
Have updated the plugin. Just tested and have the same behavior. ~./prettierrc is not loaded. If i copy to project document root, it works.
Are you able to reproduce this issue ?

will try to run the prettier cli outside vim and see if it will find it in user's home. According to how config resolver works, it seems like it will fail.

Will keep you posted.
Thanx for your effort and feedback.

**Comment by playahater** [comment]
Hey @mitermayer,

Tested with prettier cli outside of vim and as expected got the same behavior as with vim-prettier.

`prettier --config-precedence 'prefer-file' --write path/to/file`
or
`prettier --config-precedence 'file-override' --write path/to/file`

Was invoking from within the project root [ relative file path ] and the configuration was not picked up. When i copied ~/.prettierrc to a project root, it worked. was picked up by prettier script without problem.

This means that we should close this thread and move it to a https://github.com/prettier/prettier issues ?

Thanx

**Comment by mitermayer** [comment]
Hi @playahater  

Thanks for the message, we should create that issue on `prettier` repo itself and track it over there. 

Thanks for looking into this. Will close this issue on here since its an upstream issue.
