### ISSUE TITLE
Support for 'prettier-standard-formatter'

### ISSUE THREAD

**Issue by alex-shamshurin** [prettier/vim-prettier#20]
I'd like to use it both. If there are an option to specify which tool to be used?

**Comment by mitermayer** [comment]
Hi @alex-shamshurin,

Sorry but the goal of this project is to add support and evolve together with https://github.com/prettier/prettier

**Comment by alex-shamshurin** [comment]
I understand that, but I'd like make a little post-processing, pipe the output to `standart`. Is this a policy restriction?

**Comment by mitermayer** [comment]
Hi @alex-shamshurin, 

Its not a policy/restriction, however at this stage our main focus is on prettier. I am happy to revisit this issue if there is enough interest around that in the future.

Once again thank you for submitting this request and I am sorry that at this stage we won't be able to action on it.

**Comment by mitermayer** [comment]
Since there has been some more interest on supporting other CLI's (https://github.com/prettier/vim-prettier/issues/42) I am now re-opening this issue.

**Comment by mitermayer** [comment]
Still interested on working in this issue, will prioritize bumping vim-prettier to support the new prettier 1.6 features then get back to this issue

**Comment by alex-shamshurin** [comment]
Does vim-prettifier need some changes to support 1.6? As I read it just formatting a bit different..

**Comment by mitermayer** [comment]
Prettier 1.6 adds support for user defined custom configuration, I want to think what would be the best way to integrate that feature in here

**Comment by alex-shamshurin** [comment]
I think project .prettierrc file must have the highest priority and only then .vimrc

**Comment by mitermayer** [comment]
Do people still think its worth integrating with other CLI's ? or is the prettier configuration settings via .prettierrc enough these days ?

**Comment by mitermayer** [comment]
This is same as https://github.com/prettier/vim-prettier/issues/148
