### ISSUE TITLE
incosistent with prettier cli and introducing syntaxt error.

### ISSUE THREAD

**Issue by aranmohyeddin** [prettier/vim-prettier#200]
I have the following file and it's called test.vue
```
<template>
  <div>
    <span>
      {{ video.selected ? "This video is included in the charts" : "This video is not included in the charts" }}
    </span>
  </div>
</template>
```
I run `prettier test.vue` and I get:
```
<template>
  <div>
    <span>
      {{
        video.selected
          ? "This video is included in the charts"
          : "This video is not included in the charts"
      }}
    </span>
  </div>
</template>
```
But I do :Prettier in vim and I get:
```
<template>
  <div>
    <span>
      {{ video.selected ? "This video is included in the charts" : "This video is not
      included in the charts" }}
    </span>
  </div>
</template>
```
which is actually syntax error.

**Comment by mitermayer** [comment]
Hi @aranmohyeddin,

Would you mind providing some information to help me debug this issue ?

From inside `vim` whats the output of ?

* `:PrettierCliVersion`
* `:PrettierCliPath`
*`:PrettierVersion`

and from your command line, whats the output of `prettier --version` and `vim --version`

Thanks a lot!

**Comment by aranmohyeddin** [comment]
1.16.3
/home/blah/node_modules/.bin/prettier
0.2.7
1.18.2
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 29 2019 20:38:53)

**Comment by aranmohyeddin** [comment]
Please tell me if you need any other information on this.

**Comment by mitermayer** [comment]
This issue has been fixed on `release/1.x` branch 

Closing this for now
