### ISSUE TITLE
How to format unsaved buffer?

### ISSUE THREAD

**Issue by ondrejsevcik** [prettier/vim-prettier#205]
Hi, I have a workflow where I paste some JSON into vim to examine it and then I want to format it. But unless I save it first with `.json` extension, I'm getting parsing errors from prettier.

Is there a way to run `:Prettier` with some argument to tell it it is a JSON?

Thanks

**Comment by mitermayer** [comment]
hi @ondrejsevcik,

From `vim-prettier` on `release/1.x` we pass through the name of the `buffer` to the `prettier` cli. This means if you name the buffer `foo.json` and run `:Prettier` you can have it formatted without saving the file.

I usally do that a lot myself, open vim and do a `:e temp.json` and paste contents then do a `:Prettier`.

**Comment by mitermayer** [comment]
Will close this issue as it was a question, if the above does not work please feel free to comment on this issue and i will reopen it and further look into it
