### ISSUE TITLE
release/1.x: prettier plugins do not work when installed with pnpm

### ISSUE THREAD

**Issue by andykais** [prettier/vim-prettier#211]
**Do you want to request a *feature* or report a *bug*?**

**What is the current/expected behavior?**
the prettier plugin `prettier-plugin-svelte` should work when installed on a project. It does work with npm, it does not work with [pnpm](https://pnpm.js.org/). I suspect the same issue will occur with any prettier plugin. I can create a repro repo if it helps.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
`1.0.0-alpha`

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
`1.18.2`

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
`/hom/andrew/Build/dev/andykais.github.io.sapper/node_modules/.bin/prettier`

**Did this work in previous versions of vim-prettier and/or prettier ?**
it works when installing with `npm`.

works:
```bash
npm i -D prettier-plugin-svelte prettier
```
does not work:
```bash
pnpm i -D prettier-plugin-svelte prettier
```

**Comment by mitermayer** [comment]
At this stage we don't currently support `pnpm` feel free to submit a PR to add support to it. 

In the meantime will be closing this issue and may re-open this in the future if we get enough bandwidth to get into it and if pnpm become mainstream

**Comment by NicoCevallos** [comment]
@andykais you could use the plugin with `--plugin=./node_modules/prettier-plugin-svelte` in the CLI. I found that here: https://github.com/prettier/prettier/issues/8056#issuecomment-623401847
Maybe not the best idea, but it works
