### ISSUE TITLE
TypeScript is formatted as PHP (1.x)

### ISSUE THREAD

**Issue by garetmckinley** [prettier/vim-prettier#219]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current/expected behavior?**
Prettier is failing to format my TypeScript file because it's interpreting it as PHP.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
1.0.0-alpha

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.18.2

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**

**Did this work in previous versions of vim-prettier and/or prettier ?**
It works when I format it using the VSCode prettier formatter.

**More Info**
I'm using NeoVim v0.4.3

When I run `:Prettier`, the buffer gets replaced with:
```
(node:18626) UnhandledPromiseRejectionWarning: Error: Invalid trailingComma value. Expected "all", "none", "php5" or "php7.2", but received "es5".
    at _loop (/home/garet/.vim/plugged/vim-prettier/node_modules/prettier/bin-prettier.js:7887:63)
    at Normalizer._applyNormalization (/home/garet/.vim/plugged/vim-prettier/node_modules/prettier/bin-prettier.js:8000:13)
    at applyNormalization (/home/garet/.vim/plugged/vim-prettier/node_modules/prettier/bin-prettier.js:7817:49)
    at Normalizer.normalize (/home/garet/.vim/plugged/vim-prettier/node_modules/prettier/bin-prettier.js:7823:9)
    at normalizeOptions$1 (/home/garet/.vim/plugged/vim-prettier/node_modules/prettier/bin-prettier.js:8760:31)
    at Object.normalizeApiOptions (/home/garet/.vim/plugged/vim-prettier/node_modules/prettier/bin-prettier.js:8918:10)
    at getOptionsForFile (/home/garet/.vim/plugged/vim-prettier/node_modules/prettier/bin-prettier.js:44160:69)
    at /home/garet/.vim/plugged/vim-prettier/node_modules/prettier/bin-prettier.js:44214:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:18626) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18626) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My `.prettierrc` is:

```
{
  "trailingComma": "es5"
}
```

The prettier plugin configuration in my `init.vim` is:

```
Plug 'prettier/vim-prettier', {
  \ 'do': 'yarn install',
  \ 'branch': 'release/1.x',
  \ 'for': [
    \ 'javascript',
    \ 'typescript',
    \ 'css',
    \ 'less',
    \ 'scss',
    \ 'json',
    \ 'graphql',
    \ 'markdown',
    \ 'vue',
    \ 'lua',
    \ 'php',
    \ 'python',
    \ 'ruby',
    \ 'html',
    \ 'swift' ] }
```

**Comment by scull7** [comment]
I'm having the same issue with my JavaScript files using `NVIM v0.4.3`

**Comment by garetmckinley** [comment]
😕 hopefully we can get some sort of input. Curious whether it's the version or something else. There's nothing in the file that should trigger php detection. I'm on a new computer this week, so I'll give it a try. Maybe there's something that I'll learn or will help narrow down.

Are you using nvm?

**Comment by mitermayer** [comment]
Hi All, 

Can you provide some snippets for me to test this, in order for me to submit a patch for it ?

**Comment by mmFooD** [comment]
I have the same issue for `.js` files, apart from that my buffer isn't replaced. I added this 
```
@@ -17,14 +17,16 @@ function! prettier#job#runner#onError(errors) abort
   if g:prettier#quickfix_enabled
     call prettier#bridge#parser#onError(a:errors, g:prettier#quickfix_auto_focus)
   endif
+  echo 'Errors'
+  echo a:errors
 endfunction
```
to get a more descriptive error message on the command-line:
`['[error] Invalid trailingComma value. Expected "all", "none", "php5" or "php7.2", but received "es5".']`

All that should be needed to reproduce is to add the `"trailingComma": "es5"` option to `.prettierrc`, no?

**What version of vim-prettier are you using - (output of :PrettierVersion) ?**
1.0.0-alpha

**What version of prettier are you using - (output of :PrettierCliVersion) ?**
1.19.1

Issue is present in both Vim 8.2.1-343 and Nvim  v0.4.3  NVIM

There is a similar issue here, that appears to be fixed. [prettier/plugin-php](https://github.com/prettier/plugin-php/issues/964) although I am not sure how relevant it is to this issue.

**Comment by mitermayer** [comment]
That is what i suspected, looks like its due to upstream prettier CLI. I will work on this today and submit a patch here. Include more info here and possibly submit an issue/fix for upstream prettier

**Comment by mitermayer** [comment]
This issue has been fixed
