### ISSUE TITLE
Package.json configuration not loaded properly (release 1.x)

### ISSUE THREAD

**Issue by sheoak** [prettier/vim-prettier#221]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current/expected behavior?**
eslint command line should have equivalent behavior, but prettier doesn't load the package.json file properly

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
1.0.0-alpha

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.19.1

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
/tmp/test-prettier/node_modules/.bin/prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**
no

vim options:
```
" prettier
let g:prettier#exec_cmd_async = 1
let g:prettier#quickfix_enabled = 0
let g:prettier#quickfix_auto_focus = 0
let g:prettier#autoformat = 0
let g:prettier#config#config_precedence = 'file-override'
```

``` 
git status
On branch release/1.x
Your branch is up to date with 'origin/release/1.x'.
```

package.json
```
{
  "name": "testing",
  "version": "0.0.0-development",
  "private": true,
  "scripts": {},
  "dependencies": {},
  "devDependencies": {
    "eslint": "^6.7.2",
    "eslint-config-prettier": "^6.7.0",
    "eslint-plugin-prettier": "^3.1.2",
    "prettier": "^1.19.1"
  },
  "eslintConfig": {
    "env": {
      "browser": true,
      "node": true,
      "es6": true
    },
    "root": true,
    "extends": [
      "eslint:recommended",
      "plugin:prettier/recommended"
    ],
    "rules": {
      "semi": 0,
      "prettier/prettier": [
        "error",
        {
          "semi": false
        }
      ]
    }
  }
}
```

File test.js:
```javascript
function hello() {
  console.log("please do not add semi")
}

hello()
```

Test in command line (working):
```
eslint test.js
# empty
```

In vim (not working):
```json
:Prettier
# is adding semi colons
```

If I remove prettier configuration in the package.json, then eslint adds the semi colons in command line, so the configuration is working. I read https://github.com/prettier/vim-prettier/issues/51
but I'm using 1.19 so I think it should work?

**Comment by mitermayer** [comment]
Prettier configuration is not read from `eslintConfig` please refer to `prettier/prettier` or the main website for more information on how to configure it
