### ISSUE TITLE
Add support for `prettier 2.x` 

### ISSUE THREAD

**Issue by mitermayer** [prettier/vim-prettier#232]
This issue was track work to ensure `vim-prettier` plays nicely with `prettier` 2.x

Will update the description of this issue in the next few days when I get a better idea on the scope

*** 

Did some preliminary work on local branch and will add some tasks that need to be done in order to address this issue:

- [ ] Update `vim-prettier` defaults to match `prettier 2.x` and move existing defaults to `classic` preset
- [ ] Ensure backwards compatibility with `prettier 1.x` 
- [ ] Create a "Classic" preset to still enable support for folks that cannot upgrade to prettier 2.0
- [ ] Ensure all existing supported plugins are working with `prettier 2.x`
- [ ] Update README to guide users on how to default to old `classic` preset

**Comment by mikabytes** [comment]
Not sure if this comment belongs in this issue, so let me know and I'll move it:

I'm seeing a strange issue that trailing commas are being removed in vim-prettier when in use with prettier version 2.0.1. I have no configuration file and all `g:prettier` lines are removed from my vimrc file.

Executing `prettier --write file.js` on the command line does the right thing (trailing commas are added).

**Comment by mitermayer** [comment]
Hi @mikabytes thanks for adding this info to this issue. I will work on it over the weekend, if you find any other issues please comment in here.

Thanks a lot !

**Comment by ariabuckles** [comment]
I'm having a similar issue with parens; I think it's because [this plugin's defaults](https://github.com/prettier/vim-prettier/blob/eda018b6af2983758db06ce0ad6139f5b0651861/plugin/prettier.vim#L109`) no longer line up with prettier's.

Maybe it's possible to only pass the [cli arguments](https://github.com/prettier/vim-prettier/blob/49d91743b2df43f84edd199f877d494b4d8812f4/autoload/prettier/resolver/config.vim#L21) when those options are defined?

Thanks for your work on this @mitermayer !

**Comment by mikabytes** [comment]
That's awesome @mitermayer 

Yes, can confirm that the parens issue. Just noticed that one myself.

**Comment by stevematdavies** [comment]
Using prettier 2, causes the plugin to fail with 'failed to parse buffer'. I cannot use it any longer until there is a fix for this.

**Comment by mitermayer** [comment]
Sorry all, been kept busy with family at home (3 kids).  I have a fix for supporting it already. Will publish a new version today.

Sorry for the delay in this issue and any inconvenience

**Comment by mitermayer** [comment]
@stevematdavies  ^^

**Comment by stschindler** [comment]
I'm using the plugin with Prettier 2.0.9, and it keeps ignoring the `allowParens = "always"` configuration. This is the default starting from 2.0.0, but the plugin keeps removing parenthesis from single-parameter arrow functions. Any idea?
