### ISSUE TITLE
Installation fails in post-update hook using vim plug

### ISSUE THREAD

**Issue by tusharkant15** [prettier/vim-prettier#237]
**Do you want to request a *feature* or report a *bug*?** NO

**What is the current/expected behavior?** PlugInstall fails with the following command
```x Post-update hook for vim-prettier ... Exit status: 243```

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?** 0.2.7

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?** 2.0.4

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?** Blank

**Did this work in previous versions of vim-prettier and/or prettier ?** First time using this plugin

My .config/nvim/init.vim

```
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'mattn/emmet-vim'
Plug 'posva/vim-vue'
Plug 'prettier/vim-prettier', { 'do': 'npm install', 'branch': 'release/0.x' }
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'
Plug 'honza/vim-snippets'

call plug#end()
```

**Comment by dakyskye** [comment]
Same here.

**Comment by dakyskye** [comment]
fixed for me.

**Comment by mitermayer** [comment]
Sorry ill look into this

**Comment by germanamz** [comment]
@dakyskye What did you do?

**Comment by dakyskye** [comment]
@germanamz as far as I remember, I just installed Node and Yarn.

**Comment by tusharkant15** [comment]
I'm closing this issue as recently setting up a new environment, this issue has been resolved.
