### ISSUE TITLE
PrettierFragment not work 

### ISSUE THREAD

**Issue by hneis** [prettier/vim-prettier#241]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current/expected behavior?**
I select php text fragment and use PrettierFragment nothnig happens.
If i use Prettier all text formatted correctly. 
I use PrettierFragment to html text and it work correctly.
**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
1.0.0-alpha
**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
2.0.5
**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
/home/username/nvim/plugged/vim-prettier/node_modules/.bin/prettier
**Did this work in previous versions of vim-prettier and/or prettier ?**

**Comment by mitermayer** [comment]
Sorry this is duplicate of https://github.com/prettier/vim-prettier/issues/232
