### ISSUE TITLE
:Prettier fills the default register with “x”

### ISSUE THREAD

**Issue by bpierre** [prettier/vim-prettier#244]
On Neovim, formatting a file replaces the default register by `x`.

The issue gets fixed by commenting these three lines: https://github.com/prettier/vim-prettier/blob/master/autoload/prettier/utils/buffer.vim#L11-L15

The cursor stays in place even after having commented these lines − is it really needed on Neovim?

- `:PrettierVersion` => 1.0.0-alpha
- `:PrettierCliVersion` => 2.0.5
- Did this work before? => I am not sure, I was using a custom function to call the prettier CLI before, and I don’t remember if the move to the Vim plugin corresponds to my default register getting “randomly” replaced by `x` (it took me a while to identify the cause!).

**Comment by skylarmb** [comment]
👏  i was going crazy today over this! couldnt figure out what i was doing that was causing this.

**Comment by felipellrocha** [comment]
Oh my god, thank you for this. I had no idea which plugin was doing this.

**Comment by okkan** [comment]
Horrible bug ! Really annoying.
