### ISSUE TITLE
Support prettier-stylelint

### ISSUE THREAD

**Issue by jsit** [prettier/vim-prettier#255]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current/expected behavior?**
Currently `vim-prettier` does not support [`prettier-stylelint`](https://github.com/hugomrdias/prettier-stylelint)

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
1.0.0-alpha

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
1.19.1

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
/..current-directory../node_modules/.bin/prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**
No

---

`prettier-stylelint` can apply rules from stylelint to the Prettier output. [`prettier-atom`](https://github.com/prettier/prettier-atom) for instance supports this. It would be useful for this plugin to support it as well.

**Comment by jfroffice** [comment]
I am trying to use the `prettier-stylelint` with following setting
> `au FileType css,scss let b:prettier_exec_cmd = "prettier-stylelint --fix"`

the configuration does not seem to be apply correctly. The double quotes are transformed in single quote.

The right configuration is with double quote in the `.stylelintrc` file.
