### ISSUE TITLE
trailing_comma = 'es5' setting not working

### ISSUE THREAD

**Issue by haruki-m** [prettier/vim-prettier#258]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current/expected behavior?**
Current:
`let g:prettier#config#trailing_comma = 'none'` and `let g:prettier#config#trailing_comma = 'all'` works perfectly, but`let g:prettier#config#trailing_comma = 'es5'` gives me an error message in vim: `Prettier: failed to parse buffer`

Expected:
Setting `let g:prettier#config#trailing_comma = 'es5'` shouldn't give me an error message and should work.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
`1.0.0-alpha`

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
`1.19.1^@`

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
`/Users/[name]/.vim/plugged/vim-prettier/node_modules/.bin/prettier`

**Did this work in previous versions of vim-prettier and/or prettier ?**
Not sure

**Comment by jasonkit** [comment]
This should be related to https://github.com/prettier/plugin-php/issues/964
A quick workaround is upgrade @prettier/plugin-php version to latest version

**Comment by mitermayer** [comment]
Did a new release and no longer can reproduce this issue, if you still having problems feel free to reopen
