### ISSUE TITLE
ftdetect collides with default filetype settings (specifically typescriptreact or tsx)

### ISSUE THREAD

**Issue by gadkadosh** [prettier/vim-prettier#273]
My experience is specifically with typescriptreact, where vim-prettier changes the default typescriptreact to typescript. This breaks my completion plugin, for example, which depends on typescriptreact for jsx apparently. 

The question is why should vim-prettier touch those filetype detections at all? I feel like if they get correctly set by default vim or nvim, vim-prettier shouldn't interfere. Maybe it's from a time when those were not set correctly?

**Comment by yzia2000** [comment]
It seems to format for me regardless of the filetype. Let me make a pr to adjust this

**Comment by gadkadosh** [comment]
Just for my curiosity: why does vim-prettier have to declare filetypes at all? Why not leave that to vim runtime or to specialised plugins? Is it a best practice because it has ftdetects?

**Comment by yzia2000** [comment]
This is just a guess but I believe they felt that certain filetypes might not interface well with prettier, or probably an early bug fix. I myself would rather stick to vim runtime.
