### ISSUE TITLE
markdown file: an unordered list and 3 spaces between dash and item

### ISSUE THREAD

**Issue by adampaulukanis** [prettier/vim-prettier#283]
**Do you want to request a *feature* or report a *bug*?**

It is probably a bug

**What is the current/expected behavior?**

When I have a markdown file like this for instance:
`# TODO
- one
- two
- three`

Notice there is only one space between '-' and first character.

And I like it that way.

After issuing `:Prettier` I get something like that:

`# TODO
- ___one
- ___two
- ___three`

There are 3 spaces between '-' and first character.

Is it intentional? Does it matter at all?

I guess I can live with that but I somehow like it when there is only one space between them.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**

1.0.0-beta

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**

2.2.1^@

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**

prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**

No idea, I have just started using vim-prettier.

Does it do that way in relation to [this](https://www.markdownguide.org/basic-syntax/#adding-elements-in-lists)?

**Comment by adampaulukanis** [comment]
Now I realized that it has something to do with tabs. Sorry for the noise.

**Comment by kasir-barati** [comment]
@adampaulukanis I am experiencing the same situation and dunno exactly what is wrong. I installed VSCode on my Manjaro, then installed Prettier. Created a `README.md` file and tried to add a list like this:

```markdown
- Some list
````

But after I saved it, I had this:
```markdown
-   Some list
```

It is really annoying :disappointed:, if you solved it please share how you did it so I can get rid of it and change it back to the way it was.

**Comment by adampaulukanis** [comment]
Hi @kasir-barati sadly, I do not remember much from it.

It may help you or not. I was using *Vim*, and there is an option called `shiftwidth`. It was set in my case to 4, after changing it to 2 I got what I wanted.
