### ISSUE TITLE
Cursor position lost when multiple panes open on same buffer

### ISSUE THREAD

**Issue by callumacrae** [prettier/vim-prettier#318]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current/expected behavior?**

When I run `:Prettier` and I have the same file open in multiple split panes, the cursor position is lost in all panes other than the one I ran `:Prettier` from and sent to the bottom.

It's expected that the cursor position would be preserved on all panes.

Steps to replicate:

- Open a pretty long JS file
- Navigate to about halfway through the file
- `:vsplit`
- Insert a few blank lines (or something else that will cause prettier to modify the buffer)
- `:Prettier`

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**

1.0.0-beta

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**

2.3.2 (but have replicated on other projects on more up-to-date versions)

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**

[pwd]/node_modules/.bin/prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**

Nope.

https://github.com/neoclide/coc-prettier handles this correctly but I don't use coc anymore!

**Comment by byeokim** [comment]
Possible duplicate of #248. Not yet resolved.

**Comment by callumacrae** [comment]
yep, looks like it!
