### ISSUE TITLE
Prettier auto format on Save not working.

### ISSUE THREAD

**Issue by iJKTen** [prettier/vim-prettier#342]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current/expected behavior?**
It appears that when I save in `nvim` prettier does not automatically run. I can manually trigger prettier by `<leader>p` or running `:Prettier`. Running `echo g:loaded_prettier` returns `1` and `echo g:prettier#autoformat` returns `0`. 

I have the following in my `.vimrc` file
```
let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0
```

I am using `Packer` as my plugin manager and this is how the plugin is installed
```
use {
  'prettier/vim-prettier',
  run = 'npm install',
}
```

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
1.0.0-beta

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
2.8.5^@

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
`/users/<name>/dev/folder/node_modules/.bin/prettier`

**Did this work in previous versions of vim-prettier and/or prettier ?**
First time running it.

Thank you so much for taking the time to look into this!

**Comment by mitermayer** [comment]
Fixed by https://github.com/prettier/vim-prettier/pull/348
