### ISSUE TITLE
Why prettier keeps adding warn messages on top of my document?

### ISSUE THREAD

**Issue by bumasello** [prettier/vim-prettier#344]
I just got Prettier installed on my neovim setup, and everytime ai activate it, it includes some messagens on top of my document. How can I disable it?

![image](https://github.com/prettier/vim-prettier/assets/107157948/4b8bb1be-d70e-4d6e-b664-cde8548e0bd5)

**Comment by zoominGiladSher** [comment]
This seems like a problem with the new version of Prettier (3.0.0) being a major version with breaking changes that are not yet supported by the plugin. Hoping that the creators will update it, but doubt it since it has not been committed to in a few years...

**Comment by bumasello** [comment]
So I have to uninstall prettier on windows and nvim and install an older version?

**Comment by zoominGiladSher** [comment]
The way that I solved it was by changing the package files locally since this repo doesn't seem very maintained:
1. in `autoload/prettier/resolver/config.vim` I changed the function `prettier#resolver#config#resolve to use the following (removed depracated `jsx-bracket-same-line` and changed `loglevel` cli argument  to `log-level` code:
```vim
" By default we will default to our internal
" configuration settings for prettier
function! prettier#resolver#config#resolve(config, hasSelection, start, end) abort
  " Allow params to be passed as json format
  " convert bellow usage of globals to a get function o the params defaulting to global
  " TODO: Use a list, filter() and join() to get a nicer list of args.
  let l:cmd = s:Flag_use_tabs(a:config) . ' ' .
          \ s:Flag_tab_width(a:config) . ' ' .
          \ s:Flag_print_width(a:config) . ' ' .
          \ s:Flag_parser(a:config) . ' ' .
          \ s:Flag_range_delimiter(a:config, a:hasSelection, a:start, a:end) . ' ' .
          \ ' --semi=' .
          \ get(a:config, 'semi', g:prettier#config#semi) .
          \ ' --single-quote=' .
          \ get(a:config, 'singleQuote', g:prettier#config#single_quote) .
          \ ' --bracket-spacing=' .
          \ get(a:config, 'bracketSpacing', g:prettier#config#bracket_spacing) .
          \ ' --arrow-parens=' .
          \ get(a:config, 'arrowParens', g:prettier#config#arrow_parens) .
          \ ' --trailing-comma=' .
          \ get(a:config, 'trailingComma', g:prettier#config#trailing_comma) .
          \ ' --config-precedence=' .
          \ get(a:config, 'configPrecedence', g:prettier#config#config_precedence) .
          \ ' --prose-wrap=' .
          \ get(a:config, 'proseWrap', g:prettier#config#prose_wrap) .
          \ ' --html-whitespace-sensitivity ' .
          \ get(a:config, 'htmlWhitespaceSensitivity', g:prettier#config#html_whitespace_sensitivity) .
          \ ' --stdin-filepath="'.simplify(expand('%:p')).'"' .
          \ ' --require-pragma=' .
          \ get(a:config, 'requirePragma', g:prettier#config#require_pragma) .
          \ ' --end-of-line=' .
          \ get(a:config, 'endOfLine', g:prettier#config#end_of_line) .
          \ ' --log-level error '.
          \ ' --stdin '

  return l:cmd
endfunction
```
2. In `plugin/prettier.vim` I removed the following code:
```vim
" put > on the last line instead of new line
" default: 'false'
" See more: https://prettier.io/docs/en/options.html#jsx-brackets
let g:prettier#config#jsx_bracket_same_line = get(g:,'prettier#config#jsx_bracket_same_line', 'false')
```

**Comment by LordPax** [comment]
PR that solve the problem : https://github.com/prettier/vim-prettier/pull/345

**Comment by zoominGiladSher** [comment]
It only solves the log-level issue, `jsx-bracket-same-line` is not there and is still deprecated @LordPax

**Comment by gregorywaynepower** [comment]
@mitermayer Is this something you have the bandwidth to deal with?

**Comment by caiangums** [comment]
> It only solves the log-level issue, `jsx-bracket-same-line` is not there and is still deprecated @LordPax

@zoominGiladSher I just updated the `log-level` locally at my env and it stopped complaining about the `jsx-bracket-same-line`. It could be because I'm writing `*.tsx` files at a Next.js personal project 🤔 

Thanks @LordPax 🙏

**Comment by gregorywaynepower** [comment]
@bumasello Was there a pull request that fixed this issue?

**Comment by nickhealy** [comment]
@bumasello i am also getting this issue still, why have you closed the issue?

**Comment by trabeast** [comment]
Also experiencing this issue.

**Comment by jrledezma** [comment]
> @bumasello Was there a pull request that fixed this issue?

is this available?
because I'm just download again the plugin and I don't see this has been fiexed

**Comment by gregorywaynepower** [comment]
Looks like this may be resolved in #345 according to @mitermayer .

**Comment by nusendra** [comment]
Still got this issue with prettier ^3. It's working fine on 2.5.1 version. So i will use this version (2.5.1) for now

**Comment by JudeDavis1** [comment]
Why is this closed? This issue is still happening

**Comment by nusendra** [comment]
@JudeDavis1 yup this still happening.

**Comment by AmoghCreator** [comment]
@nusendra yup, 2.5.1 seems to be the only viable option rn with this issue. I am unable to implement the fix shared by @zoominGiladSher for my lua config. I will try to look for the latest version that works without a hitch, 2.5.1 and forwards.
