### ISSUE TITLE
Deprecated / Unknown options when using Prettier v3

### ISSUE THREAD

**Issue by fortes-codaio** [prettier/vim-prettier#346]
This plugin uses `--jsx-bracket-same-line` which is deprecated, along with `--loglevel` and `--stdin` which are no longer supported. This means if you run `:Prettier` now, you'll get the following three lines at the top of the file

```
[warn] --jsx-bracket-same-line is deprecated.
[warn] Ignored unknown option --loglevel=error. Did you mean --log-level?
[warn] Ignored unknown option --stdin.
```

**Comment by btjanaka** [comment]
Can confirm. I've switched to using Neoformat but I suspect there are some nuanced options that this plugin provides but Neoformat does not / can not.

**Comment by kzKallisti** [comment]
https://github.com/prettier/vim-prettier/pull/345
