### ISSUE TITLE
Keep show warning after save!

### ISSUE THREAD

**Issue by jonahfang** [prettier/vim-prettier#347]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current/expected behavior?**
1.exec 'Prettier' on javascript file buffer.
2.save it.
3.change again.
4.save it.
5.expected without warning: 'This file has changed since it was read it'.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
1.0.0-beta

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
v3.0.3

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
prettier

**Comment by mitermayer** [comment]
Fixed by https://github.com/prettier/vim-prettier/pull/348
