### ISSUE TITLE
prettier runs with incorrect prettier configuration

### ISSUE THREAD

**Issue by akoskm** [prettier/vim-prettier#352]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current/expected behavior?**
When I run prettier with <leader>p, it formats the file one way; when I run prettier from VSCode, it formats the file a bit differently.
We have a pre-commit hook in the project, and unfortunately, the formatting applied by Vim is incorrect.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**
1.0.0

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**
2.8.8

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**
`/Users/akoskm/Projects/my-project/node_modules/.bin/prettier`

**Did this work in previous versions of vim-prettier and/or prettier ?**
No information.

Here's my `prettierrc.js` file:

```
const originalConfig = require('eslint-config-my-project/.prettierrc');

// ---------------------------------------------------------------------------------------
// NOTE: When we upgrade to prettier 3.x.x we should uncomment the `ignorePath` and remove
// the `.prettierignore` file.
// ---------------------------------------------------------------------------------------
module.exports = {
  ...originalConfig,
  // ignorePath: '.eslintignore',
};
```

And the contents of `~/.vimrc`:
```
let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0
let g:prettier#autoformat_config_present = 1
let g:prettier#exec_cmd_async = 1
```

**Comment by gkoberger** [comment]
I'm running into this same problem, specifically with `trailingComma`, which was changed from 'es5' to 'all' in Prettier v3.0.0. (vim-prettier is still using the old default)

If I explicitly set it in my config, it works correctly. But if I omit it, it doesn't. My prettier version is indeed correct (according to `:PrettierCliVersion`), as is my `:PrettierCliPath`, and I can't track down what the issue might be.

**Comment by gkoberger** [comment]
Hey, I ran into this too. After a lot of debugging, it seems like vim-prettier is overriding prettier defaults with its own.

Here's my issue: https://github.com/prettier/vim-prettier/issues/353

Here's where the overriding is happening: https://github.com/prettier/vim-prettier/blob/master/plugin/prettier.vim#L58

I bet you'll find the property you're having is overridden in the prettier.vim file.

A short-term fix is to add your own `let g:prettier#config#CONFIG_YOURE_WORRIED_ABOUT` in your `~/.vimrc` to override their overriding.

**Comment by akoskm** [comment]
I switched to LazyVim, so I can't really reproduce this, but I hope your comment will help those who want to get this working in their custom setup - without LazyVim. Thanks @gkoberger.
