### ISSUE TITLE
:Prettier causes :Ggrep to lose history

### ISSUE THREAD

**Issue by trungdq88** [prettier/vim-prettier#39]
Thanks for awesome plugin. Can you take a look at this?

**without `:Prettier`** this should to through the matches list of 'abc'

(in vim)
```
:Ggrep 'abc'
:cnext
:cnext
:cnext
```

**with `:Prretier`**
```
:Ggrep 'abc'
:Prettier
:cnext -----> Cause E42: No Errors
:cnext
```
Image:
![image](https://user-images.githubusercontent.com/4214509/29226254-85c92636-7efb-11e7-877a-3ca356ca4f08.png)

GIF:
![prettier](https://user-images.githubusercontent.com/4214509/29226458-5b72c490-7efc-11e7-94d7-d4de6b046cd2.gif)

**Comment by mitermayer** [comment]
Hi @trungdq88 

Thanks for submitting this issue, will have a look into it during the weekend

**Comment by trungdq88** [comment]
Thanks. That's very nice response time.
