### ISSUE TITLE
Using prettier-eslint-cli

### ISSUE THREAD

**Issue by mightyguava** [prettier/vim-prettier#42]
Can this be configured to use https://github.com/prettier/prettier-eslint-cli? We have some eslint rules that are incompatible with prettier that work great with the alternate CLI. It's also a great tool as we try to migrate to prettier without completely turning off eslint

**Comment by mitermayer** [comment]
@mightyguava thanks for submitting this issue, 

In the past we had also been requested to add support for other CLI's (`prettier-standard-formatter` (https://github.com/prettier/vim-prettier/issues/20))

So maybe now it make sense to revisit this and enable it to be configurable for other CLI's. 

cc @alex-shamshurin

**Comment by mitermayer** [comment]
Still interested on working in this issue, will prioritize bumping vim-prettier to support the new prettier 1.6 features then get back to this issue

**Comment by dedoyle** [comment]
can I use prettier-eslint-cli by this config
`let g:prettier#config#config_precedence = 'prettier-eslint'`

**Comment by mitermayer** [comment]
Hi @dedoyle,

The `configPrecedence` option is basicly what prettier gives to use:

so if you do on the CLI `prettier --help` you can get more information on the available options:

```
  --config-precedence <cli-override|file-override|prefer-file>
                           Define in which order config files and CLI options should be evaluated.
                           Defaults to cli-override.
```

To answer your question, `'prettier-eslint'` is not a valid option

**Comment by dedoyle** [comment]
I'm looking forward to you to complete this issue. Atom has a prettier-atom, and I had tried it. It feels great. But I still hope I can do it in vim, do not want to leave vim to atom. Thank you very much for vim-prettier.

**Comment by mitermayer** [comment]
Hi @dedoyle,

`vim-prettier` supports prettier **custom configuration files** (https://prettier.io/docs/en/configuration.html#basic-configuration) have thought about creating a `prettier.config.js` with the settings required for your project ? you could even add one of those to your home directory.

example of one (https://github.com/facebook/draft-js/blob/master/prettier.config.js):

```javascript
module.exports = {
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: false,
  jsxBracketSameLine: true,
  parser: 'flow',
};
```

**Comment by dedoyle** [comment]
prettier doesn't have some config like space-before-function-paren. how to fix it

![image](https://user-images.githubusercontent.com/12028922/32926691-8f65884a-cb83-11e7-8111-aa5f861e0e5e.png)

after prettier
![image](https://user-images.githubusercontent.com/12028922/32926706-a6b51f88-cb83-11e7-9e11-5637f79da7cf.png)

![image](https://user-images.githubusercontent.com/12028922/32926715-bb36072e-cb83-11e7-87f5-0186595459bc.png)

**Comment by alex-shamshurin** [comment]
@dedoyle This is one reason as far as know to use prettier-eslint

**Comment by mitermayer** [comment]
Hi @alex-shamshurin ,

It is on our roadmap for 1.0 release https://github.com/prettier/vim-prettier/projects/1, still trying to find time to action on it. 

Before starting adding support for other CLI's I want to setup the automated testing infrastructure for `vim-prettier` to make sure no regressions will be introduce during the refactor. But hopeful to get into that soon!

**Comment by alex-shamshurin** [comment]
Hi, is there any update?

**Comment by mitermayer** [comment]
Do people still think its worth integrating with other CLI's ? or is the prettier configuration settings via `.prettierrc` enough these days ?

**Comment by dedoyle** [comment]
It will be great to support prettier-eslint-cli

**Comment by docwhat** [comment]
I don't think you can get the functionality of `prettier-eslint-cli` from just a `.prettierrc` file.  I'd love to be proven wrong though.

**Comment by alex-shamshurin** [comment]
If some option, like 'use_eslint_fix' is set then it should read one of eslint config files and run eslint --fix after prettier.

**Comment by docwhat** [comment]
> If some option, like 'use_eslint_fix' is set then it should read one of eslint config files and run eslint --fix after prettier.

Are you saying such an option exists and that it is the same as `prettier-eslint`?

Or that it would be good if such an option exists?

**Comment by Industrial** [comment]
It should not be limited to ESLint only (I use csslint as well and it acts on different file extensions), and instead should be configurable.

I think having a situation where the tools to be ran on which file-type much like `lint-staged` is preferrable; https://github.com/prettier/vim-prettier/issues/148

**Comment by mitermayer** [comment]
This is same as https://github.com/prettier/vim-prettier/issues/148
