### ISSUE TITLE
PrettierAsync does not work on Windows

### ISSUE THREAD

**Issue by boojinks** [prettier/vim-prettier#46]
I've just installed the package and whilst calling :Prettier works fine, :PrettierAsync appears to do absolutely nothing.

As far as I can tell, this is caused by the fact that Vim's job_start function is attempting to call the prettier executable directly, which causes the job to fail immediately (job_status returns 'fail') without ever calling the error callback. The correctly working :Prettier goes via a system() call which executes the command via the shell rather than a direct call.

If I prepend 'cmd.exe /C' to the command passed to job_start, it works just fine.

I will put in a fix and create a pull request when I get the chance but I can't guarantee it will be pretty.

**Comment by mitermayer** [comment]
@boojinks Thank you for reporting this issue, a PR for it would be awesome!

**Comment by mitermayer** [comment]
I have just managed to reproduce this issue, a PR on it would be amazing :)

**Comment by mitermayer** [comment]
@boojinks Thank you very much for helping out with this issue! I have just done a release (0.0.14) with that fix
