### ISSUE TITLE
`--parser` with value `postcss` is deprecated

### ISSUE THREAD

**Issue by nathanspecht** [prettier/vim-prettier#59]
This line is being prepended to my *.css files when formatting with vim-prettier:

`--parser` with value `postcss` is deprecated. Prettier now treats it as: `--parser=css`.

I am using prettier version 1.7.1.

**Comment by mitermayer** [comment]
Hi @nathanspecht thanks for reporting that, will work on a fix for it tonight and do a new release

**Comment by mitermayer** [comment]
this is also happening 

https://github.com/prettier/prettier/issues/2936

**Comment by samumist** [comment]
Had the same problem.

**Comment by mitermayer** [comment]
Trying to figure out a solution for this problem, in the meantime if you guys can use an older prettier version 1.7.0 that would be great.

I have just pushed to master a pin to force using prettier 1.7.0 dependency version while I try to figure out how to fix things in here and on prettier itself, so please update `vim-prettier` and 

in the meantime you can do that by:

```vim
let g:prettier#exec_cmd_path='~/.vim/plugged/vim-prettier/node_modules/.bin/prettier'
```

**Comment by mitermayer** [comment]
Just did a 0.1.3 release that should fix this issue. Please feel free to reopen if you still have the same problems
