### ISSUE TITLE
Overwrites Buffer1 with contents of Buffer2

### ISSUE THREAD

**Issue by alanhamlett** [prettier/vim-prettier#62]
Probably from a race condition where saving then immediately switching to a different buffer, the buffer switched to is overwritten with the contents from the previous buffer.

**Comment by mitermayer** [comment]
Hi @alanhamlett,

Thanks for reporting this! Just managed to reproduce it. Will start looking into it during the weekend.

**Comment by mitermayer** [comment]
just did a new release with a fix for this issue

**Comment by mitermayer** [comment]
@alanhamlett just did another follow up release to enable formatting on switched buffers
