### ISSUE TITLE
No references to getting help or support

### ISSUE THREAD

**Issue by dfishburn** [prettier/vim-prettier#67]
vim-prettier 0.2.3

I have installed and using it now, thank you for the plugin.

doc\prettier.txt makes no mention on how to ask for help or support on the plugin.
No website given or email address supplied.

The only way I found this website was opening the changelog.md.

Most plugin authors put headers at the top of **each** of the files with something like this:
```
" vim-prettier.vim - A vim plugin wrapper for prettier 
" ---------------------------------------------------------------
" Version:       0.2.3
" Author:    Whatever <you.want at gmail dot com>
" Last Modified: 2017 Aug 13
" Created:       2017-05-24
" Homepage:      http://www.vim.org/scripts/script.php?script_id=5572
" Contributors:  Blah...
"                Blah
"
" Help:         :h vim-prettier.txt
```

This helps people find support as well as when I prune files from my plugins directory (if the filename wasn't obvious) I know which plugin it was for.

And of course doc\vim-prettier.txt should have similar information or a section for getting help / support / kudos and so on.

**Comment by dfishburn** [comment]
Sorry, I see you have this section in plugin\prettier.vim:
```
"==========================================================================================================
" Name Of File: prettier.vim
"  Description: A vim plugin wrapper for prettier, pre-configured with custom default prettier settings.
"   Maintainer: Mitermayer Reis <mitermayer.reis at gmail.com>
"      Version: 0.2.3
"        Usage: Use :help vim-prettier-usage, or visit https://github.com/prettier/vim-prettier
"
"==========================================================================================================
```

Strangely that was the last spot I looked, it really should have been the second spot after the prettier.txt file.

Comment still applies (all files), but sorry for not noticing this first.

**Comment by mitermayer** [comment]
Hi @dfishburn,

Will include the above comment on all the other files. Also accepting a PR. 

Thanks for reporting it :)

**Comment by dfishburn** [comment]
You might also want to reference the github link in the description of your [plugin](http://www.vim.org/scripts/script.php?script_id=5572).  Many other people do this.
