### ISSUE TITLE
plugins should reference global variable

### ISSUE THREAD

**Issue by dfishburn** [prettier/vim-prettier#68]
To prevent a script from being loaded and reloaded and reloaded, Vim files add (*.vim) typically add the following to the top of them:

```
if exists('g:loaded_vim_prettier') || &cp
    finish
endif
let g:loaded_vim_prettier = 0.2.3
```

That way they get loaded once and only once.  Once the functions and initialization is complete, there is no need to re-source this file.

**Comment by mitermayer** [comment]
Hi @dfishburn,

Please not that we have this logic on https://github.com/prettier/vim-prettier/blob/master/plugin/prettier.vim#L14

```vim
if exists('g:loaded_prettier')
  finish
endif
let g:loaded_prettier = 1
```

**Comment by dfishburn** [comment]
One thing I am not certain on, when you reference a function in the autoload file, whether Vim automatically sources that file first and then calls it or whether it checks if the function exists and does not source it.

I just that standard patter in all my files.

**Comment by mitermayer** [comment]
Hi @dfishburn 

Autoloaded function get evaluated only once and are also lazy loaded. This is a good reference: http://learnvimscriptthehardway.stevelosh.com/chapters/53.html

Some quotes from the above link

>` :call somefile#Hello()`
    When you run this command, Vim will behave a bit differently than a normal function call.
    If this function has already been loaded, Vim will simply call it normally.
    Otherwise Vim will look for a file called autoload/somefile.vim in your ~/.vim directory (and any Pathogen bundles).
    If this file exists, Vim will load/source the file. It will then try to call the function normally.

**Comment by mitermayer** [comment]
Once again thanks @dfishburn  for raising this issue,

Feel free to comment/re-open this issue if you have any further questions or any info around it

**Comment by dfishburn** [comment]
Actually from that web link you provided:
```
Vim already has a definition for example#Hello, so it doesn't need to reload the file, which means:

The code outside the function wasn't run again.
It didn't pick up the changes to the function.

Now run :call example#BadFunction(). 

You'll see the loading messages again, as well as an error about a nonexistent function. 

But now try running :call example#Hello() again. This time you'll see the updated message!
```

That is the case I am talking about.
Once you reference a **different** function in the **same** file, a function that Vim has not used yet, it sources the file again.

Had you not defined all your functions using `function!`, you would have seen an error (function already exists) each time you call a different function.

So, for efficiency you do want the `finish` guard at the top of that file.

**Comment by mitermayer** [comment]
Will look into this later and get back to this issue, in the meantime will leave it open until I can can check on it more in depth

**Comment by mitermayer** [comment]
Hi @dfishburn,

In order to debug the above statement I have just performed the following test, edited `autoload/prettier.vim` and included on the top the following line:

```viml
echom "loading vim-prettier"
```

Then I did the following steps:

1. Opened a new file 
2. Executed `:Prettier`
3. Executed `:PrettierCliVersion`
4. run the command `:messages` to check for the printed messages

outcome:

- "loading vim-prettier" got printed only once regardless of the multiple calls, so the autoload file got only loaded once

If you can provide a working example of that I will be happy to re-open this issue.
