### ISSUE TITLE
Add support for prettier 1.8

### ISSUE THREAD

**Issue by mitermayer** [prettier/vim-prettier#77]
We should add support for prettier 1.8

- [x] Bump internal plugin dependency
- [x] Add support for markdown formatting
- [x] Update readme and docs

**Comment by mitermayer** [comment]
latest version of prettier breaks `vim-prettier` error handling since they changed their default CLI error display

before was:

```
a.js: SyntaxError: Unexpected token (5:7)
  3 |  */
  4 | 
> 5 | const (a,b,c,asdasd) => {const b    =3}
    |       ^
 6 |
```

now it is:

```
[error] a.js: SyntaxError: Unexpected token (5:7)
[error]   3 |  */
[error]   4 | 
[error] > 5 | const (a,b,c,asdasd) => {const b    =3}
[error]     |       ^
[error]   6 | 
```

***

changes like that makes upgrading `prettier` a breaking change for `vim-prettier` since it wont be able to support older versions of prettier.

cc @lydell @azz

**Comment by mitermayer** [comment]
prettier 1.8+ also caused https://github.com/prettier/vim-prettier/issues/76

**Comment by lydell** [comment]
Why won’t you be able to support older versions of Prettier because of the error message change?

**Comment by mitermayer** [comment]
Hi @lydell,

> Why won’t you be able to support older versions of Prettier because of the error message change?

In that case it was not a problem since we were able to have one sigle regex to match them all (otherwise we would have to version check prettier on initialization to know which regex to use)

But due to the nature that `vim-prettier` uses the CLI API, simple changes like changing the message output can cause problems and unseen breaks

**Comment by lydell** [comment]
We should be more careful in the future, then.

**Comment by lydell** [comment]
We should be more careful in the future, then.

**Comment by lydell** [comment]
We should be more careful in the future, then.
