### ISSUE TITLE
Single quote option not working

### ISSUE THREAD

**Issue by josemarluedke** [prettier/vim-prettier#84]
The option to use single quote is not working. 

I have the following in my vimrc:

```
let g:prettier#config#single_quote = 'true'
```

Current using Prettier version is 1.9.1.

**Comment by haochuan** [comment]
Same issue.
Current using Prettier version is 1.9.1.

**Comment by mitermayer** [comment]
Looking into this now, may be some new incompatibility of the new prettier version

**Comment by mitermayer** [comment]
Turns out this is a regression from `prettier` itself https://github.com/prettier/prettier/issues/3432, will mitigate this problem now by disabling `editorConfig` compatibility until the next release of `prettier` where that gets fixed

**Comment by mitermayer** [comment]
https://github.com/prettier/vim-prettier/issues/83 also caused by the same above problem
