### ISSUE TITLE
Override for proseWrap option

### ISSUE THREAD

**Issue by ffky** [prettier/vim-prettier#88]
Hi! There is a `--prose-wrap` option for markdown files since 1.8.2 and was hoping we could configure this option through the plugin's config. Thanks! (If you are open to a PR for it please let me know) 

https://prettier.io/docs/en/options.html#prose-wrap

**Comment by mitermayer** [comment]
Hi @ffky,

Please feel free to submit a PR!

**Comment by mitermayer** [comment]
Merged on https://github.com/prettier/vim-prettier/pull/90
