### ISSUE TITLE
How do I enable trailing commas?

### ISSUE THREAD

**Issue by EdmundMai** [prettier/vim-prettier#95]
I would like to enable trailing commas. Instead of the formatter changing my code from:

```
  Promise.all([
    sendToAlphaBroker(firstHalfOfByteChunks, file),
    sendToBetaBroker(lastHalfOfByteChunks, file),
  ]).then(() => {
    console.log("Upload complete!");
  });

```

to

```
  Promise.all([
    sendToAlphaBroker(firstHalfOfByteChunks, file),
    sendToBetaBroker(lastHalfOfByteChunks, file)
  ]).then(() => {
    console.log("Upload complete!");
  });

```
  

I added this line: `let g:prettier#config#trailing_comma = 'all'` to my vimrc file but it doesn't seem to be working?

**Comment by mitermayer** [comment]
Hi @EdmundMai,

I have just tested your snippet and it works. What may be happening on your case is that you may be trying to format a file that lives somewhere where a `prettier` configuration file exists along the ancestry, in that case `vim-prettier` will always respect the project configuration.

You can test that assumption by creating a file on a different folder outside your project with the contents and making sure that on your `.vimrc` you have the `let g:prettier#config#trailing_comma = 'all'
` line that you mentioned

```javascript
 Promise.all([
    sendToAlphaBroker(firstHalfOfByteChunks, file),
    sendToBetaBroker(lastHalfOfByteChunks, file)
  ]).then(() => {
    console.log("Upload complete!");
  });
```

and then running `:Prettier` on it and checking the expected result. 

If the above fails it maye mean that you may have a global prettier configuration file define somewhere along the ancestry of your file.

***

Please feel free to re-open / comment on this issue if that does not solve your problem.
